### ISSUE TITLE
Questions about Multi-QueueInc

### ISSUE THREAD

**Issue by MrWLeo** [NetSys/bess#1037]
I have tried to use Multi QueueInc to connect to a port, but each time only one queue can receive the packet and the others are always 0. Is there any solution?

**Comment by krsna1729** [comment]
If you check the demo video, there is setting `ddp` that needs to be enabled, along with Intel Columbiaville (CVL) NIC. More info here https://doc.dpdk.org/guides-20.11/nics/ice.html#prerequisites

This essentially enables the NIC to parse GTPU headers and get to the UE IP to hash and distribute. Without this the NIC is hashing only on the outer IP addresses. There are 2 issues - 1. less entropy in outer L3/L4 to do RSS 2. same UE IP can end up on different core depending on N3, N9 or N6.

**Comment by sarsanaee** [comment]
Hi @MrWLeo  Did you solve your problem?

**Comment by MrWLeo** [comment]
> 

Yep. Put different src/dst IP in the packet header. BESS seems use a hash by the outer IP to map the queue port

**Comment by sarsanaee** [comment]
Makes sense.
