### ISSUE TITLE
How to do tcpdump ?

### ISSUE THREAD

**Issue by chaitanyalala** [NetSys/bess#125]
Hi,

I would like to add the ability to do a "tcpdump" or "mirror" on packets coming in from PMD port and destined towards VPort (ideally in both directions).
So far I have not been able to understand how to define that pipeline in a .bess file.

I tried something on the lines of the following but it does not work. How would we get this to work ? Is there a known format for this ?

```
v = VPort()
p = PMDPort(port_id=0)
PortInc(port=p) -> rewrite::Rewrite() -> bpf::BPF() -> PortOut(port=v)
PortInc(port=v) -> PortOut(port=p)

```

**Comment by sangjinhan** [comment]
For simple tapping for debugging, you don't need any special modules. Mirroring packets at a gate of any module is a built-in feature of BESS. In bessctl, you can try:
```
localhost:10514 $ tcpdump port_inc0 0 -ne | less
```

There are other approaches to do the same thing: e.g., while there is no module that mirrors packets and send them out to downstream modules, it should be simple to implement one (with a few lines of code). Then create such a mirror module and connect it to two downstream path. One is for usual packet processing and the other for inspection on mirrored packets (with UnixSocketPort you can export packets to an external program).

**Comment by chaitanyalala** [comment]
Thank you! Will try this and report back.
