### ISSUE TITLE
when running bessctl, an SyntaxError raised 

### ISSUE THREAD

**Issue by xnhp0320** [NetSys/bess#13]
Traceback (most recent call last):
  File "./bessctl", line 9, in <module>
    import commands
  File "/home/hepeng/bess/bessctl/commands.py", line 507
    exec(code in new_globals, locals())
SyntaxError: unqualified exec is not allowed in function '_do_run_file' it contains a nested function with free variables

**Comment by intelsai** [comment]
-        exec(code, new_globals)
+        exec code in new_globals

**Comment by xnhp0320** [comment]
Thanks.

**Comment by sangjinhan** [comment]
Fixed the issue by not using the nested function. For compatibility with Python 3, I'll keep the exec as a function call (not a statement) for now...
