### ISSUE TITLE
Where is the vhost driver?

### ISSUE THREAD

**Issue by royceniu** [NetSys/bess#200]
Hi, 

I am testing the release of BESS v0.2. I cannot add a vhost for my kvm VM. And I cannot find the vhost driver in core/driver folder.

So, how to add a vhost port for BESS v0.2?

Edit:
I found you abandoned Vhost driver at https://github.com/NetSys/bess/commit/184f8b560cbf792bf65f92d6591a6af38437978c

But, is there an instruction on how to use kvm nic in following versions of BESS? The old instructions on wiki doesn't work. 

Thanks!

**Comment by sangjinhan** [comment]
Thank you for the report. We recently retired the vhost driver and switched to the DPDK PMD driver for vhost-user. Please check the updated page:

https://github.com/NetSys/bess/wiki/Hook-up-a-VM-to-BESS

**Comment by royceniu** [comment]
Thx, sangjin.
