### ISSUE TITLE
bessctl: error in _choose_arg error handling

### ISSUE THREAD

**Issue by MurphyMc** [NetSys/bess#23]
When passed both positional and keyword args, [_choose_arg](https://github.com/NetSys/bess/blob/develop/bessctl/commands.py#L504)() attempts to raise an exception and fails (resulting in an exception, but -- you know -- not the right one :) ).

There are two problems here.  First, `bess` isn't in scope.  I think this can be fixed by removing the `staticmethod` decorator and using `self.bess`.  The second issue is that I think `Error` is the wrong exception here (as evidenced by the wrong number of constructor arguments, I believe), but I'm not sure what the right one is.

**Comment by sangjinhan** [comment]
Thanks. bess.Error was meant to be errors from bess daemon process, so clearly it was a wrong one. I am not sure what exception type it should be either... but it seems that a typical python program would have used just standard TypeError exception.
