### ISSUE TITLE
invalid SN_PORTS in pktgen

### ISSUE THREAD

**Issue by dsocer** [NetSys/bess#28]
It looks like the pktgen does not release port correctly when input an invalid SN_PORTS:

run perftest/pktgen SN_PORTS=3
*** Error: Port id 1 is not available
  BESS daemon response - errno=19 (ENODEV: No such device)

localhost:10514 $ run perftest/pktgen SN_PORTS=1
*** Error: rte_eth_dev_configure() failed
  BESS daemon response - errno=16 (EBUSY: Device or resource busy)

**Comment by sangjinhan** [comment]
Could you try again with the latest code? There were patches to fix the bug, which caused no reset on ports and modules in some situations.

**Comment by sangjinhan** [comment]
Closing as I checked that the issue doesn't appear on my system any longer. (feel free to reopen if the issue persists)
