### ISSUE TITLE
Connecting VMs to BESS

### ISSUE THREAD

**Issue by mitaliyad** [NetSys/bess#314]
Hello All,
We are doing a bess setup for inter-VM communication on the same host. We were looking through the GitHub page and bess wiki but are unable to find how to assign bess port to a VM. Please help us in setting up VM vNIC in bess setup.

Thanks

**Comment by mitaliyad** [comment]
Hi,

We have created a module which in turn creates 2 ports of driver type VPort and create two pipeline (vport0->vport1 and vport1->vport0) in the host machine. Now we want to export these vports to two VMs such that it gives faster inter-VM communication.
Please help us in this regard.

Thanks

**Comment by melvinw** [comment]
Hi,

Sorry about the lack of documentation about this scenario. It has been materializing over the past few weeks and will be finalized soon.

I just added some documentation on how to create vhostuser-baked PMDPorts and how to connect them to VMs [here](https://github.com/NetSys/bess/wiki/Hooking-up-BESS-Ports#connecting-vms-with-bess). Documentation for VPorts and containers will appear shortly.

Hope that helps! Let me know if you have any more questions.

Melvin

**Comment by mitaliyad** [comment]
Hi,
Thanks for the link. It did help us creating the port but we are facing issue in assigning this PMDPort to VM. We are using virt-manager to create/manage VMs. So to add extra qemu command line argument similar to given in link, we added them to guest VM's xml file like this:
<domain xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
...
...
 <qemu:commandline>
   <qemu:arg value='-chardev'/>
   <qemu:arg value='socket,id=mychr0,path=/tmp/my_vhost0.sock'/>
   <qemu:arg value='-netdev'/>
   <qemu:arg value='vhost-user,id=mydev0,chardev=mychr0,vhostforce,queues=1'/>
   <qemu:arg value='-device'/>
   <qemu:arg value='virtio-net-pci,netdev=mydev0'/>
  </qemu:commandline>
</domain>

But switching on the VM, we are getting error: unable to connect to socket: Permission denied.
We have opened virt-manager from root login.
So please help us in how to connect this socket to VM via virt-manager?

Thanks

**Comment by melvinw** [comment]
Though you're starting virt-manager as root, libvirt may be configured to run as `nobody` in some other group (probably `kvm`) and by default DPDK vhost chardevs are only owner writable (root in this case). Can you post the output of your libvirt `qemu.conf`? I think it lives in `/etc/libvirt/` by default. Running the command below before booting your VM should do the trick.

```
sudo chmod g+w /tmp/my_vhost0.sock
sudo chown root:<LIBVIRT_GROUP> /tmp/my_vhost0.sock
```

A simpler, though not recommended, solution might be to add `user = "root"` to `qemu.conf`.

**Comment by mitaliyad** [comment]
Thanks!
Now both our VMs are able to boot but both are getting same MAC address. The bessd.INFO log file shows an mmap error when the second VM boots up. The first VM boots without any issue. We are attaching the log file (name: log24_2.txt) with this post. 
The bess module that we are using is :

v1::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=1')
v2::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=1')

PortInc(port=v1.name) -> PortOut(port=v2.name)
PortInc(port=v2.name) -> PortOut(port=v1.name)

Here two VM are getting two vhost sockets.
We thought it might be an memory issue. So, we increased the huge page allocation in the host but it did not resolve the issue.

Please guide us on it.

[log24_2.txt](https://github.com/NetSys/bess/files/799086/log24_2.txt)

**Comment by melvinw** [comment]
You can add `,mac=<SOME_MAC>` to the `-device` flag value to give the interfaces different MAC addresses.

Can you clarify how you're using the vhost sockets? Are you attaching both vhost sockets to both VMs, or are you attaching `my_vhost0` to one VM and `my_vhost1` to the other? I'm not sure that the former is supported by DPDK vhost (though you could try adding more queues to each interface). If you're doing the latter, having your VM allocate its memory from hugepages by adding the following to your qemu command line may help. 

```
-m MEMORY_AMOUNT
-object memory-backend-file,id=mem,size=MEMORY_AMOUNT,mem-path=/path/to/hugepages,share=on -mem-prealloc -numa node,memdev=mem 
```

**Comment by mitaliyad** [comment]
Hi Melvin,
Thanks a lot! It did help us.
Regarding the setup, we are creating two PMDPort v1 and v2. v1 is assigned to VM1 and v2 is assigned to VM2. Now memory issue is not there and both VMs are able to boot properly but there is no communication between the VMs. (because the client VM shows No route to host when trying to connect to the server VM).  The client and servers VMs are running iperf3. 

On the host, bess script we are using is:
v1::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=1')
v2::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=1')

PortInc(port=v1.name) -> PortOut(port=v2.name)
PortInc(port=v2.name) -> PortOut(port=v1.name)

i.e. whatever is coming to v1 forward it to v2 and vice-versa. But on doing 'show port' there are no packets coming to v1 or v2.
Also, we are assigning same mac to VMs as their respective PMDPort socket's mac on host.

**Comment by melvinw** [comment]
Great! Have you configured the interfaces and setup routes inside the guest? If so, can you post the output of `ip link` and `ip route`? 

Otherwise, assuming your vhost interfaces show up as `ethX` in your guests and you want them to talk over `10.0.0.0/8`, that should boil down just running something like the following in each guest

```
ifconfig 10.A.B.C/8 up
ip route add 10.0.0.0/8 dev ethX
```

Hope that helps!

**Comment by mitaliyad** [comment]
Yes, we have configured the interface and the route. But still we are unable to communicate between the VMs.
Please find attached the network configurations of our VMs. Also, we just did the bess setup as given in the BESS setup page. Do we need to run the dpdk_setup.sh for running PMDPorts?

Also, we could not run the bess.yml file as it is. So, we manually installed all the packages that were listed in the yml file, skipping the docker part and the setup under the vagrant tag, as we felt it was all for container. 

![vm1_network](https://cloud.githubusercontent.com/assets/19935384/23355866/ae5cc498-fcfd-11e6-9ecc-63577672e807.png)
![vm2_network](https://cloud.githubusercontent.com/assets/19935384/23355867/ae62a340-fcfd-11e6-9b7e-c0ea324ebd4d.png)

**Comment by sangjinhan** [comment]
Perhaps you need to disable virtio offloading features. Try adding `csum=off,...` to your QEMU configuration as below:
```-device virtio-net-pci,netdev=XXX,id=YYY,mac=52:54:00:00:00:01,csum=off,gso=off,guest_tso4=off,guest_tso6=off,guest_ecn=off,mrg_rxbuf=off```

**Comment by mitaliyad** [comment]
We tried the offloading feature too, But still the VMs cannot communicate.

**Comment by sangjinhan** [comment]
I am not sure whether 00:00:00:00:00:00 is a valid MAC address accepted by the kernel network stack. Could you try with 02:xx:xx:xx:xx:xx?

Also, it might be worth trying tcpdump, to check whether packets disappear in the middle or rejected at the receiver.

**Comment by mitaliyad** [comment]
Yes we changed the MAC of the VMs and also did the tcpdump. What we noticed is that the ping request is not going out of the VM itself. In the capture, the request is not shown in the ethX interface but it is getting captured in lo interface. We are unable to understand the issue.
We are attaching the xml of the VM because we feel there might be some issue in the way we are providing the interface to the VM. We are also attaching the wireshark capture.
![wireshark_vm_ping_mar1](https://cloud.githubusercontent.com/assets/19935384/23457596/982495be-fe9e-11e6-8dbd-1bc3a26bd242.png)
[vm_dpdk.xml.pdf](https://github.com/NetSys/bess/files/810499/vm_dpdk.xml.pdf)

Please help us.

**Comment by sangjinhan** [comment]
The Wireshark screen shows you are using the same IP address for both source and destination. Please check if you specified distinct MAC/IP addresses for the VMs.

**Comment by Priyanka-Naik** [comment]
Yes. We have assigned different ip and MAC to both the VMs. 192.168.100.2 (02:00:00:00:00:01) and 192.168.100.3(02:00:00:00:00:02).  But still the Wireshark shows the packets do not go out of the VM  and take the same ip and hence we could not capture the Packets on ethX interface but saw the packets on localhost interface. We are not able to understand why are the packets not going out of ethX.

**Comment by sangjinhan** [comment]
Could you post the result of the following commands on each VM?
```
$ ip l
$ ip a
$ ip r
$ ip n
```

**Comment by mitaliyad** [comment]
Below are the results of the above commands on both the VMs. We have set the IP on both the VMs using network manager giving the gateway as 0.0.0.0. As seen from the ip n command the arp is failing. Do we need to set an IP to the bess switch to act as the gateway? If so what is the command for the same.

![vm1_ip txt](https://cloud.githubusercontent.com/assets/19935384/23495214/69062e92-ff3d-11e6-8fda-34251ad11f4b.png)
![vm2_ip txt](https://cloud.githubusercontent.com/assets/19935384/23495215/69079016-ff3d-11e6-8d5f-f9b797d63635.png)

**Comment by sangjinhan** [comment]
The configuration appears to be ok. For further digging, could you also post statistics counters?

```
(in the VMs)
$ ip -s a

(in the host)
$ bessctl show port
```

**Comment by mitaliyad** [comment]
below are the details. We also tried adding static arp entry into the VM but it is giving : No buffer space available issue when we do ping and the packets do not get captured on any interfcae.  

localhost:10514 $ show port
  my_vhost0/PMDPort (56:48:4f:53:54:00)
    Incoming (external -> BESS):
      packets: 0
      dropped: 0
      bytes  : 0
    Outgoing (BESS -> external):
      packets: 0
      dropped: 0
      bytes  : 0
  my_vhost1/PMDPort (56:48:4f:53:54:01)
    Incoming (external -> BESS):
      packets: 0
      dropped: 0
      bytes  : 0
    Outgoing (BESS -> external):
      packets: 0
      dropped: 0
      bytes  : 0

![vm1_ip_s txt](https://cloud.githubusercontent.com/assets/19935384/23500386/dc070a02-ff55-11e6-8cf1-ba569195e34c.png)
![vm2_ip_s txt](https://cloud.githubusercontent.com/assets/19935384/23500385/dbdb211c-ff55-11e6-9553-c5c407f8a8c4.png)

**Comment by sangjinhan** [comment]
I wonder why on your machine `ip -s a` doesn't show stats like this...
```
...
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 0c:c4:7a:db:0d:5c brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.23/16 brd 192.168.255.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::ec4:7aff:fedb:d5c/64 scope link
       valid_lft forever preferred_lft forever
    RX: bytes  packets  errors  dropped overrun mcast
    4216200    6052     0       0       0       0
    TX: bytes  packets  errors  dropped carrier collsns
    961317     16129    0       0       0       0
```

Which Ubuntu version are you using on the VM? (and the host?)

**Comment by mitaliyad** [comment]
ubuntu version on guest and host both is 14.04.

**Comment by sangjinhan** [comment]
Some suggestions:

FYI, tools like `ping` and `arping` provide options you can specify an interface that packets are forced to go through (thus bypassing L3 IP forwarding lookup).

Given that all the statistics numbers are zero, I suspect the problem resides at the low level (initialization of virtual NICs). There are several inspection points you can take a look:
* In the VM, 
  * Does `dmseg` shows anything interesting/suspicious, regarding eth0 or virt0?
  * `sudo lspci -vvv` shows the virtio-net device correctly?
* In the host,
  * `/tmp/bessd.INFO` should show some log messages for vhost-user activities.
  * `ps aux | grep qemu`, to figure out what the actual QEMU command-line options are being used by libvirt.

For various tests I often use 14.04 in a VM so it shouldn't be a problem. One culprit might be the version of QEMU...? I think the QEMU package that comes with Ubuntu 14.04 is quite old. Perhaps you can update QEMU (e.g., build from source) and try again? Or ideally, consider trying 16.04 for both host and guest, if you can spare more time.

**Comment by krsna1729** [comment]
if you are ok with installing newer QEMU on 14.04 using PPA, here is the [link](https://launchpad.net/~syseleven-platform/+archive/ubuntu/virtualization)

**Comment by krsna1729** [comment]
Qemu 2.2 is needed for vhost-user. Newer versions have multi-q support. I used to add a PPA for 14.04 which doesn't exist anymore. So either compile QEMU from the source or use 16.04 host like @sangjinhan suggested

**Comment by krsna1729** [comment]
Aside - It's better to remove the global `-mem-prealloc` flag and move it into the object describing the hugepages itself as shown. This will save some trouble if the user is passing other objects that don't play well with that flag. 

`-object memory-backend-file,id=mem,size=MEMORY_AMOUNT,mem-path=/path/to/hugepages,prealloc=on,share=on -numa node,memdev=mem`

Do test :)

**Comment by Priyanka-Naik** [comment]
Thanks a lot for the help!!!! We re-did the whole setup on ubuntu16.04 in PM as well as VM. **The VMs could communicate. :-)**
On running iperf3 in the VMs (with BESS setup on the host ) we saw that the UDP throughput as 9.35 Gbps while iperf3 gave us 20 Gbps with kvm-virtio setup.
 Is there some performance tuning required so that BESS would give us better performance? i.e. Increasing the cores provided to BESS or increasing memory provided to BESS?

**Comment by Priyanka-Naik** [comment]
We have a simple pipeline in BESS module on host and we would like to use the multicore duplication feature (i.e. duplicating the pipeline) of BESS to improve the performance. Can you provide us commands to do the same? Also, can you please give us some idea on improving the performance further.

Thanks a lot :-)

**Comment by mitaliyad** [comment]
Hi,

We have one doubt. Although we are able to communicate between two VMs using iperf3, but on running our dpdk application (udp sender/receiver) inside VM we see that packets from VM1 are not reaching VM2. 
We are observing using show port on host that the packets are showed in the incoming queue of PMDPort1 (which assigned to VM1) but are dropped at the outgoing queue of PMDPort2 (assigned to VM2). 
In our VMs we are using uio_pci_generic driver to provide vNIC to DPDK applications running on the VMs.
Here is our bess script:
```

my_vhost0::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=1')
my_vhost1::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=1')

input0::QueueInc(port=my_vhost0, qid=0) #This module will read from my_vhost0 on queue 0
input1::QueueInc(port=my_vhost1, qid=0) #This module will read from my_vhost1 on queue 0

output0::QueueOut(port=my_vhost0, qid=0) #This module will write to my_vhost0 on queue 0
output1::QueueOut(port=my_vhost1, qid=0) #This module will write to my_vhost1 on queue 0

input0 -> output1
input1 -> output0
```

and here is show port stats before and after running our test:
```
localhost:10514 $ show port
  my_vhost0/PMDPort (56:48:4f:53:54:00)
    Incoming (external -> BESS):
      packets: 1,293,791,739
      dropped: 0
      bytes  : 54,372,404,201
    Outgoing (BESS -> external):
      packets: 50,774,329
      dropped: 254,149
      bytes  : 75,490,633,533
  my_vhost1/PMDPort (56:48:4f:53:54:01)
    Incoming (external -> BESS):
      packets: 51,028,478
      dropped: 0
      bytes  : 75,856,255,285
    Outgoing (BESS -> external):
      packets: 1,445,447
      dropped: 1,292,346,292
      bytes  : 93,855,437
localhost:10514 $ show port
  my_vhost0/PMDPort (56:48:4f:53:54:00)
    Incoming (external -> BESS):
      packets: 1,353,902,091
      dropped: 0
      bytes  : 56,897,038,985
    Outgoing (BESS -> external):
      packets: 50,774,329
      dropped: 254,149
      bytes  : 75,490,633,533
  my_vhost1/PMDPort (56:48:4f:53:54:01)
    Incoming (external -> BESS):
      packets: 51,028,478
      dropped: 0
      bytes  : 75,856,255,285
    Outgoing (BESS -> external):
      packets: 1,445,703
      dropped: 1,352,456,388
      bytes  : 93,866,189
localhost:10514 $ 

```

**Comment by Priyanka-Naik** [comment]
We were able to resolve the issue. There was some issue in the VM2 xml which caused this problem. Sorry for so many questions. Thanks a lot for all your constant replies which helped us solve the issue. 

Cheers to the BESS team :-)

**Comment by melvinw** [comment]
Right on! Glad everything's working. As squeezing more performance out of your setup goes, checkout https://github.com/NetSys/bess/blob/master/bessctl/conf/samples/multicore.bess for an idea about how to run your pipeline on multiple cores. Also, if your machine has NUMA support, you should see better performance by pinning your VMs to socket 0 (where BESS runs) if you aren't already. Other than those tweaks there isn't much else... the bottleneck in your case is likely the host-vm boundary.

**Comment by melvinw** [comment]
Closing and marking as solved

**Comment by Priyanka-Naik** [comment]
Hi,

We needed a clarification. Can a PMDPort export multiple queues to the VM?
