### ISSUE TITLE
Error handling when head-room is too small

### ISSUE THREAD

**Issue by nemethf** [NetSys/bess#340]
When there's not enough room to increase the size of the packet header with pkt->prepend(), then different encapsulation modules simply forward the packet unmodified.  See, for example, the 
[vxlan encapsulation module](https://github.com/NetSys/bess/blob/master/core/modules/vxlan_encap.cc#L65).  Wouldn't it be better to drop these packets, send them to a special gate, or somehow notify the pipeline writer?   

A bit unrelated, but `conf/sample/latency.bess` shows a good example how we can test the raw performance of a module or pipeline.  But is there a recommended way to test the correctness of a new module or a complex pipeline?  I was able to come up with something: [encap.bess](https://raw.githubusercontent.com/nemethf/bess/160f4c7cb2fc9ad15ab4cba8c122e6b9d085b7c2/bessctl/conf/samples/encap.bess), but I hoped there's a simpler way without using VPort and scapy's send-receive function.

(Additionally, the byte order of the value_bin in SetMetadata().Attribute is not documented and it's not straightforward to figure out what is expected.)

**Comment by justinemarie** [comment]
Re: testing correctness, there is a testing script here that automatically sends packets in and out and checks whether or not they match what one expects:
https://github.com/NetSys/bess/tree/master/bessctl/conf/testing
It is pretty basic right now, but it does some basic correctness testing for the modules that have tests implemented so far.

**Comment by justinemarie** [comment]
I agree with you that the module shouldn't just silently fail -- I'll check with @sangjinhan to see whether he prefers the "send to a special gate" or take the "resize the packet buffer" approach. I doubt drop is the right thing...

**Comment by justinemarie** [comment]
Okay, our fearless leader @sangjinhan says two things: 
(a) In a new upcoming feature (in a few months), BESS will be able to check at startup whether or not a module is likely to overflow like this and will reject the configuration entirely. This feature is still a while out though.
(b) In the mean time, it's fine to just change the module to drop packets in this case.
Would you like to make a PR to address (b), or would you like me to?

**Comment by nemethf** [comment]
So in the upcoming version the modules somehow expose how they modify packet sizes, and then the daemon can calculate whether a component in the pipeline exceeds the headroom limit, right?  That sounds really good, but unfortunately it lowers the motivation to mitigate the problems with the current version.   On the other hand, creating the pull request would serve as a good learning task.  All in all, I might return to it in the upcoming ... weeks.  Sorry.  

Thank you also for drawing my attention to the testing script.

**Comment by sangjinhan** [comment]
I think in the meantime "if the headroom is not big enough, the behavior is undefined" is enough (so by definition, no special handling is necessary). Dropping packets (or redirecting them to a special gate) also makes sense.

The following modules seem to prepend data to packet headers. All of them currently just skip encapsulation if headroom is not enough.

```
GenericEncap
VXLANEncap
VLANPush
IPEncap
EtherEncap
```
