### ISSUE TITLE
How to connect two containers across the hosts by using bess ?

### ISSUE THREAD

**Issue by 201528015059077** [NetSys/bess#35]
Hi！

![container across p-p on bess](https://cloud.githubusercontent.com/assets/11385298/18199723/3a1d8982-7134-11e6-9d99-11b3685d024d.png)

It's easy to connect containers on a single host, but how can i connect A and B across the hosts?

**Comment by sangjinhan** [comment]
Is the host NIC also managed by BESS (i.e., DPDK PMD)? Or is it just a (single) management network interface?

The first thing you need to do is to connect the container virtual port to the host NIC on each machine. There can be multiple ways to do so, but the most straightforward way is to directly connect 
them (see samples/vport.bess).

If you cannot take over the NIC from the host (e.g., there is no other NIC), packets must go through the Linux network stack anyway. I suppose (1) 

1. you create another virtual port (vp2)
2. connect vp1 and vp2 in BESS
3. connect vp2 and host1 in Linux. There are many options: ethernet bridging, IP routing, iptables rules, or tunneling (e.g., VXLAN)

**Comment by 201528015059077** [comment]
Thanks a lot.
