### ISSUE TITLE
Codecov test coverage doesn't make much sense

### ISSUE THREAD

**Issue by sangjinhan** [NetSys/bess#388]
I am somewhat puzzled by the Codecov results. Coverage graph fluctuates for some non-obvious reasons...

https://codecov.io/gh/NetSys/bess/

**Comment by justinemarie** [comment]
It also doesn't include the python tests, right? Just the C++/Google tests?

**Comment by sangjinhan** [comment]
We are not even sure about if that's the case. Need to verify :-)

**Comment by justinemarie** [comment]
Yikes!

**Comment by sirspinach** [comment]
Python tests (`./sanity_check.sh` and `bessctl -- run testing/run_module_tests`) should be included in code coverage count. At least that is how the .travis.yml is set up.

**Comment by sirspinach** [comment]
In this job, code coverage according to codecov.io fell to 4%. https://travis-ci.org/NetSys/bess/jobs/221876348

It would be nice if at the very bottom, along with submitting to codecov.io, we could see the local machine output what it thinks code coverage is.

**Comment by changlan** [comment]
Let me look into this.

**Comment by changlan** [comment]
Should be fixed by #492.

**Comment by sangjinhan** [comment]
Not sure if it was actually fixed. #499 decreases the coverage from 64% to 58%, although it is a relatively small change....

**Comment by changlan** [comment]
The number seems pretty stable now.
