### ISSUE TITLE
Issue with KMOD compile on Fedora 24

### ISSUE THREAD

**Issue by chaitanyalala** [NetSys/bess#40]
Hi,

I cannot seem to compile bess on Fedora 24 which is 4.7.x kernel based (4.7.6-200.fc24.x86_64). The problem is that in core/kmod/sndrv.c there is a check for "        if (paravirt_enabled()) {" in the sndrv_init function. This is non-existent on 4.7 kernel. Maybe we need to use a different function to check this ?

**Comment by sangjinhan** [comment]
The kernel module used to support both host and guest (with ivshmem) environments. We retired the guest mode in favor of virtio, so I can safely remove the legacy code.
