### ISSUE TITLE
KMOD disabled in Guest Mode.

### ISSUE THREAD

**Issue by chaitanyalala** [NetSys/bess#41]
Hi,

I see that this commit disabled "guest mode". I assume that means we cannot load KMOD under a para-virtualized kernel (CONFIG_PARAVIRT). My question is -
1. Why is this restriction in place ?
2. Is it going to be supported in the future ?

 git show 0ada460d
commit 0ada460d470b7c97ff15ee88b6663ad4680f5028
Author: Sangjin Han <sangjin@eecs.berkeley.edu>
Date:   Tue Dec 1 01:02:58 2015 -0800

    disable guest mode

**Comment by sangjinhan** [comment]
Yes, you can load the module in the guest (that's what I do for development and test). The patch has nothing to do with running both BESS and vport in a guest.

The "Guest Mode" refers to the case where BESS runs on the host, while the virtual port is created by the module in a guest. For this particular scenario, you can use virtio-net.

**Comment by chaitanyalala** [comment]
Thank you !
