### ISSUE TITLE
Reopen: Multi queue support for VM #346

### ISSUE THREAD

**Issue by Priyanka-Naik** [NetSys/bess#438]
Hi,

We want to export multi-queue PMDPorts to VMs (one port to one VM) connected via BESS.

Here is the script used:

```
my_vhost0::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=2',, num_inc_q=2, num_out_q=2)
my_vhost1::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=2',, num_inc_q=2, num_out_q=2)

input0::QueueInc(port=my_vhost0, qid=0) #This module will read from my_vhost0 on queue 0
input1::QueueInc(port=my_vhost1, qid=0) #This module will read from my_vhost1 on queue 0

output0::QueueOut(port=my_vhost0, qid=0) #This module will write to my_vhost0 on queue 0
output1::QueueOut(port=my_vhost1, qid=0) #This module will write to my_vhost1 on queue 0

input0 -> output1
input1 -> output0

input10::QueueInc(port=my_vhost0, qid=1) #This module will read from my_vhost0 on queue 1
input11::QueueInc(port=my_vhost1, qid=1) #This module will read from my_vhost1 on queue 1

output10::QueueOut(port=my_vhost0, qid=1) #This module will write to my_vhost0 on queue 1
output11::QueueOut(port=my_vhost1, qid=1) #This module will write to my_vhost1 on queue 1

input10 -> output11
input11 -> output10
```
The error we are getting by using this setup and running dpdk application inside VM (which uses both the queues) is:

```
EAL: Error -exiting with code:1
Cause: Cannot configure device: err=-22, port=0
```
On looking into BESS.info on the host, we saw that although VRINGS are created corresponding to second queues (i.e qid=1) but these are disabled by default.
Here is the snapshot of the BESS.info:

```
I0323 16:32:11.085374 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
I0323 16:32:11.085429 68082 dpdk.cc:64] VHOST_CONFIG: vring call idx:3 file:35
I0323 16:32:20.432083 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
I0323 16:32:20.432231 68082 dpdk.cc:64] VHOST_CONFIG: set queue enable: 1 to qp idx: 0
I0323 16:32:20.432255 68082 dpdk.cc:64] PMD: vring0 is enabled
I0323 16:32:20.432272 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
I0323 16:32:20.432282 68082 dpdk.cc:64] VHOST_CONFIG: set queue enable: 1 to qp idx: 1
I0323 16:32:20.432292 68082 dpdk.cc:64] PMD: vring1 is enabled
I0323 16:32:20.432304 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
I0323 16:32:20.432313 68082 dpdk.cc:64] VHOST_CONFIG: set queue enable: 0 to qp idx: 2
I0323 16:32:20.432323 68082 dpdk.cc:64] PMD: vring2 is disabled
I0323 16:32:20.432334 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
I0323 16:32:20.432344 68082 dpdk.cc:64] VHOST_CONFIG: set queue enable: 0 to qp idx: 3
I0323 16:32:20.432353 68082 dpdk.cc:64] PMD: vring3 is disabled
```
Here vring2 and vring3 are disabled.

Lastly, we also checked:

1) the ethtool output when the BESS port is given to the VM:

ethtool -l ens3

```
Channel parameters for ens3:
Pre-set maximums:
RX:		0
TX:		0
Other:		0
Combined:	1
Current hardware settings:
RX:		0
TX:		0
Other:		0
Combined:	1
```

2) The nb_rx_queue and nb_tx_queue the for rte_eth_dev_configure() have been configured correctly.

Kindly look into this issue.

Thank you.
Priyanka and @mitaliyad

**Comment by sangjinhan** [comment]
In the VM, `ethtool -l` should give you `Combined:  2` for `Pre-set maximums`. If it shows only 1, it indicates your QEMU is not properly configured. With the following command I was able to run virtio with multiple queues.

```
$ qemu-system-x86_64 ... \
-netdev type=vhost-user,id=...,chardev=...,queues=2 \
-device virtio-net-pci,netdev=...,id=...,mac=...,bus=...,addr=...,csum=off,gso=off,guest_tso4=off,guest_tso6=off,guest_ecn=off,mrg_rxbuf=off,mq=on,vectors=6
```

Note `queues=2` for `-netdev` and `mq=on,vectors=6` for `-device` at the end of each line. The value for `vectors` should be at least `2 * <# of queues> + 2`.

It worked with QEMU 2.5.0 (w/ apt-get on Ubuntu 16.04). It might be only me, but when I tried this on newer versions of QEMU built from source, it didn't work for me.

You can find more details at https://www.linux-kvm.org/page/Multiqueue#Enable_MQ_feature

**Comment by mitaliyad** [comment]
Hi,

Thanks for the input, we are now able to configure the multi-queue setup and able to see `Combined: 2` for `Pre-set maximums`.

Although these queues are visible inside VMs, our bess script at host machine is just forwarding packets from q0 of vm1 to q0 of vm2 and vice versa and same is the case for q1. But in our case we want to implement rss functionality inside the bess script so that packet from any queue say q0 of vm1 will forwarded to the any one of the queue of vm2 based of rss results.
It will be great help if you provide us some pointers to start with,

Thank you :-)

**Comment by mitaliyad** [comment]
Hi,

We tried to built rss functionality using HashLB(). Here is the script we are using:

```
my_vhost0::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=2',num_inc_q=2,num_out_q=2)
my_vhost1::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=2',num_inc_q=2,num_out_q=2)

i01::QueueInc(port=my_vhost0, qid=0) #This module will read from my_vhost0 on queue 0
i02::QueueInc(port=my_vhost0, qid=1) #This module will read from my_vhost0 on queue 1
o01::QueueOut(port=my_vhost0, qid=0) #This module will write to my_vhost0 on queue 0
o02::QueueOut(port=my_vhost0, qid=1) #This module will write to my_vhost0 on queue 1

i11::QueueInc(port=my_vhost1, qid=0) #This module will read from my_vhost1 on queue 0
i12::QueueInc(port=my_vhost1, qid=1) #This module will read from my_vhost1 on queue 1
o11::QueueOut(port=my_vhost1, qid=0) #This module will write to my_vhost1 on queue 0
o12::QueueOut(port=my_vhost1, qid=1) #This module will write to my_vhost1 on queue 1

i01 -> hlb01::HashLB(gates=[2], mode='l4')
i02 -> hlb02::HashLB(gates=[2], mode='l4')

i11 -> hlb11::HashLB(gates=[2], mode='l4')
i12 -> hlb12::HashLB(gates=[2], mode='l4')

hlb01:0 -> o11
hlb01:1 -> o12

hlb02:0 -> o11
hlb02:1 -> o12

hlb11:0 -> o01
hlb11:1 -> o02

hlb12:0 -> o01
hlb12:1 -> o02 
```

**Comment by sangjinhan** [comment]
Probably `show port` would be a better command than `monitor port`, since it shows accumulated numbers.

The parameter to the HashLB module should be `gates=[0, 1]`, not `gates=[2]`. I realized that the example `samples//hash_lb.bess` is incorrect. I will fix it immediately.

**Comment by mitaliyad** [comment]
Thank you.
Now we able to use muli-queue feature in bess. :)

As we are using upto 4 queues for the PMDPorts in the script, is it possible to distribute pipeline load to multiple CPU cores?

**Comment by sangjinhan** [comment]
Good to hear that it works.

Perhaps `perftest/phy_forward.bess` is the right sample to look at. The script demonstrates how to utilize multiple cores when using multi-queue ports.
