### ISSUE TITLE
Installing BESS on working system with grpc and python3 fails

### ISSUE THREAD

**Issue by GalSagie** [NetSys/bess#488]
I am not sure if thats really an issue, but currently if older versions of grpc and python3 exists on
the server the running of bessctl fails.

(I suspect that the reason is we should force python2.7 to install grpcio)

Any thoughts?

**Comment by sangjinhan** [comment]
Hm... could you try `sudo pip2 install grpcio` and check if it works..?

**Comment by GalSagie** [comment]
What fixed the issue for me was when i changed this line in packages.yaml (env):

pip: name=grpcio
To this:
pip: name=grpcio executable=pip2

I wasnt sure however if this is a good fix as the plan is to be compatible with both python3 and python2.7
(From the docs at least :))
