### ISSUE TITLE
Unable to use L2Forward() module

### ISSUE THREAD

**Issue by mitaliyad** [NetSys/bess#489]
Hi,

We are trying to communicate between two VMs connected via bess switch.

Here is script we are using at host:

```
my_vhost0::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=1')
my_vhost1::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=1')

i0::QueueInc(port=my_vhost0, qid=0) #This module will read from my_vhost0 on queue 0
i1::QueueInc(port=my_vhost1, qid=0) #This module will read from my_vhost1 on queue 0

o0::QueueOut(port=my_vhost0, qid=0) #This module will write to my_vhost0 on queue 0
o1::QueueOut(port=my_vhost1, qid=0) #This module will write to my_vhost1 on queue 0

fib = L2Forward()
fib.add(entries=[{'addr':'02:00:00:00:00:03', 'gate':0}])
fib.add(entries=[{'addr':'02:00:00:00:00:04', 'gate':1}])

i0 -> fib
i1 -> fib

fib:0 -> o0
fib:1 -> o1
```

We are trying to ping VM1 from VM2 and we saw packets coming to input queue of vm2 but neither getting drop nor its coming out of L2Forward module.

Here are the `show port ` results and show `module result`

```
show port my_host1
  my_vhost1/PMDPort (56:48:4f:53:54:01)
    Incoming (external -> BESS):
      packets: 81
      dropped: 0
      bytes  : 7,239
    Outgoing (BESS -> external):
      packets: 0
      dropped: 0
      bytes  : 0

show module l2_forward0
l2_forward0::L2Forward()
    Input gates:
          0: batches 0                packets 0                i0:0 ->, i1:0 ->
    Output gates:
          0: batches 0                packets 0                -> 0:o0
          1: batches 0                packets 0                -> 0:o1


```

Here we can see nothing is coming to l2_foward0.

Please look into this issue.

**Comment by sangjinhan** [comment]
1. Unlike output gates, input gates do not collect stats unless you explicitly turn it on. You can either:
  1. `track enable * in` to enable stats on input gates,
  1. `show module i0` to examine the output gates of `i0`, or
  1. `show pipeline` :)
1. For ping to work, please note that you will need to handle broadcast ARP requests (with destination MAC address `ff:ff:ff:ff:ff:ff`), unless you set up static ARP entries in the VM.

**Comment by mitaliyad** [comment]
Hi, I tried executing track command but some error is coming.
Here is what I am using:
`track enable [MODULE] in 0`

Error I got is:
```
Traceback (most recent call last):
  File "./bessctl", line 189, in <module>
    run_cli()
  File "./bessctl", line 166, in run_cli
    cli.loop()
  File "./bessctl", line 112, in loop
    super(BESSCLI, self).loop()
  File "/home/mythiliserver5/bess/bessctl/cli.py", line 452, in loop
    self.process_one_line()
  File "/home/mythiliserver5/bess/bessctl/cli.py", line 394, in process_one_line
    self.call_func(func, args)
  File "./bessctl", line 64, in call_func
    super(BESSCLI, self).call_func(func, args)
  File "/home/mythiliserver5/bess/bessctl/cli.py", line 369, in call_func
    func(*args)
TypeError: track_module() takes exactly 5 arguments (4 given)

```

**Comment by mitaliyad** [comment]
Also, when we are using this script: (which simply forward packet from vm1 to vm2 and vice versa)
```
my_vhost0::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=1') 
my_vhost1::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=1') 

i0::QueueInc(port=my_vhost0, qid=0) #This module will read from my_vhost0 on queue 0
i1::QueueInc(port=my_vhost1, qid=0) #This module will read from my_vhost1 on queue 0

o0::QueueOut(port=my_vhost0, qid=0) #This module will write to my_vhost0 on queue 0
o1::QueueOut(port=my_vhost1, qid=0) #This module will write to my_vhost1 on queue 0

i0 -> o1
i1 -> o0
```

we are able to ping between VMs.

Our problem is whenever l2forward module is used packet is not coming out of it. We can see packets coming to ports input queue and getting forwarded to l2forward0 module but they are not coming out of l2foward module.

**Comment by sangjinhan** [comment]
There are many options, but the most simplest would be having a `BPF` module with a `ether broadcast` filter, which redirect packets to a `Replicate` module that clones broadcast packets to all VMs.

**Comment by mitaliyad** [comment]
Ok. I think this is doable. Usually, the switch is the one who generates arp response. So is it possible to add this functionality inside our script? If yes please provide us pointers to start with. Thanks. :)

**Comment by llvilanova** [comment]
No need to implement ARP responses on the script/switch. In line with what @sangjinhan said, add a third rule in `L2Forward` for the broadcast mac, and connect it to a `Replicate` module that sends the packet to both `QueueOut` instances. The VMs will respond accordingly and everything will work.

BTW, should this issue be closed?

**Comment by muraliran** [comment]
I tried similar for containers because I haven't been able to get l2forward work with vports.
The ping did not work, arp tables weren't updated and daemon crashed after a few ping cycles. Am I missing something?
(Without L2Forward, same vports work when directly connected like in your vport examples)
Also the SetGates for Replicate is not taking in numerical value. So not sure how to extend gates if needed.

v_mlocal_1 = VPort(ifname='v_mlocal_1', docker='mlocal_1', mac_addr='02:00:00:00:11:01', ip_addrs=['10.20.21.11/24'])
v_mlocal_2 = VPort(ifname='v_mlocal_2', docker='mlocal_2', mac_addr='02:00:00:00:11:01', ip_addrs=['10.20.21.12/24'])

pML1_in::PortInc(port=v_mlocal_1)
pML1_out::PortOut(port=v_mlocal_1)
pML2_in::PortInc(port=v_mlocal_2)
pML2_out::PortOut(port=v_mlocal_2)

fib::L2Forward()
fib.add(entries=[{'addr':'02:00:00:00:11:01', 'gate':0}])
fib.add(entries=[{'addr':'02:00:00:00:11:02', 'gate':1}])
fib.add(entries=[{'addr':'ff:ff:ff:ff:ff:ff', 'gate':2}])

repl::Replicate()
repl:0 -> pML1_out
repl:1 -> pML2_out

pML1_in -> fib
pML2_in -> fib

fib:0 -> pML1_out
fib:1 -> pML2_out
fib:2 -> repl

**Comment by shinae-woo** [comment]
Hi, I'm just quick passing through, but I guess you mean `mac_addr` for `v_mlocal_2` should be `02:00:00:00:11:02`, but not `02:00:00:00:11:01`.

**Comment by shinae-woo** [comment]
I would say you might reset the number of gates like `repl.set_gates(gates=range(3))` or 
`repl.set_gates(gates=range(4))`.  You should `bess.pause_all()` and `bess.resume_all()` before/after call them.

**Comment by muraliran** [comment]
Thank you shinae-woo. The set_gates works with range param. It is python syntax - did not think about it. I do pause_all / resume in the code, so not an issue.

As for mac addr - in my setup it was correct, I pasted here wrong from a different section in my script, sorry. The ping does not work with l2forward (yet)

The arp also does not get set. After set_range properly set, there is no crash. Looking at the code the default gates for Replicate is 32 so not sure why it was failing. I'll debug later.  

After manual arp entry the traffic does not pass through.
root@cc45960f156e:/# arp
Address                  HWtype  HWaddress           Flags Mask            Iface
10.20.21.11              ether   02:00:00:00:11:01   C                     v_mlocal_2

root@8fc5082d3962:/# arp
Address                  HWtype  HWaddress           Flags Mask            Iface
10.20.21.12              ether   02:00:00:00:11:02   CM                    v_mlocal_1


root@cc45960f156e:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
16: v_mlocal_2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default
    link/ether 02:00:00:00:11:02 brd ff:ff:ff:ff:ff:ff
    inet 10.20.21.12/24 scope global v_mlocal_2
       valid_lft forever preferred_lft forever

root@8fc5082d3962:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
19: v_mlocal_1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default
    link/ether 02:00:00:00:11:01 brd ff:ff:ff:ff:ff:ff
    inet 10.20.21.11/24 scope global v_mlocal_1
       valid_lft forever preferred_lft forever

root@cc45960f156e:/# ping 10.20.21.11
PING 10.20.21.11 (10.20.21.11) 56(84) bytes of data.
^C
--- 10.20.21.11 ping statistics ---
17 packets transmitted, 0 received, 100% packet loss, time 16126ms

**Comment by muraliran** [comment]
Update: The errors I was getting was not related to the modules used as mentioned above - something about how batches used. Perhaps it was due to my usage of some other modules like arp responder or something else I am not sure. I cleaned up my code base, synced with current master and tried my config and it works now. This can be closed.

**Comment by muraliran** [comment]
(inlined by) Module::RunSplit(unsigned short const*, bess::PacketBatch*) at /home/muralir/sdev/bess/core/module.cc:643 (discriminator 2)
         640:       num_pending++;
         641:     }
         642:
      -> 643:     batch->add(*(p_pkt++));
         644:   }
         645:
         646:   // phase 2: clear splits, since it may be reentrant.
(1): /home/muralir/sdev/bess/core/modules/arp_responder.so(_ZN12ArpResponder12ProcessBatchEPN4bess11PacketBatchE+0x144) [0x7ff63132eff4]
    ArpResponder::ProcessBatch(bess::PacketBatch*) at /home/muralir/sdev/bess/core/modules/arp_responder.cc:111
      -> 111:   RunSplit(out_gates, batch);
(2): /home/muralir/sdev/bess/core/modules/source.so(+0x76085) [0x7ff62eb8d085]
    Module::RunChooseModule(unsigned short, bess::PacketBatch*) at /home/muralir/sdev/bess/core/modules/../module.h:539
      -> 539:   (static_cast<Module *>(ogate->arg()))->ProcessBatch(batch);
     (inlined by) Module::RunNextModule(bess::PacketBatch*) at /home/muralir/sdev/bess/core/modules/../module.h:543
      -> 543:   RunChooseModule(0, batch);
     (inlined by) Source::RunTask(void*) at /home/muralir/sdev/bess/core/modules/source.cc:101
      -> 101:   RunNextModule(&batch);  // it's fine to call this function with cnt==0
(3): /home/muralir/sdev/bess/core/modules/source.so(_ZN6Source7RunTaskEPv+0x20) [0x7ff62eb8d1f0]
    Source::RunTask(void*) at /home/muralir/sdev/bess/core/modules/source.cc:83
      -> 83: struct task_result Source::RunTask(void *) {
(4): /home/muralir/sdev/bess/core/bessd(_ZN4bess16DefaultSchedulerI4TaskE12ScheduleLoopEv+0x2ae) [0x64227e]
    Task::operator()() at /home/muralir/sdev/bess/core/module.h:595
      -> 595:     return module_->RunTask(arg_);
     (inlined by) bess::DefaultScheduler<Task>::ScheduleOnce() at /home/muralir/sdev/bess/core/scheduler.h:264
      -> 264:       auto ret = leaf->Task()();
     (inlined by) bess::DefaultScheduler<Task>::ScheduleLoop() at /home/muralir/sdev/bess/core/scheduler.h:246
      -> 246:       ScheduleOnce();
(5): /home/muralir/sdev/bess/core/bessd(_ZN6Worker3RunEPv+0x1cb) [0x640ffb]
    Worker::Run(void*) at /home/muralir/sdev/bess/core/worker.cc:306
      -> 306:   scheduler_->ScheduleLoop();
(6): /home/muralir/sdev/bess/core/bessd(_Z10run_workerPv+0x72) [0x641312]
    run_worker(void*) at /home/muralir/sdev/bess/core/worker.cc:320
      -> 320:   return ctx.Run(_arg);
(7): /home/muralir/sdev/bess/core/bessd() [0xd54a4f]
    execute_native_thread_routine at thread.o:?
(8): /lib/x86_64-linux-gnu/libpthread.so.0(+0x76b9) [0x7ff6352906b9]
    start_thread at ??:?
(9): /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7ff6346893dc]
    clone at /build/glibc-bfm8X4/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109
        (file/line not available)
