### ISSUE TITLE
Feature Suggestion: Expected python module for functional testing

### ISSUE THREAD

**Issue by GalSagie** [NetSys/bess#491]
Currently the repository is lacking functional testing, what i suggest is to take the example of sanity_check.py and create an "Expected" python template that runs a script and then query the bessctl for packet counters and other expected results which will enable us to build functional end to end testing.

Thoughts? would you like to see start of example code for this?

**Comment by GalSagie** [comment]
Would have set an "enhancement" label but dont have access to do it.

**Comment by GalSagie** [comment]
Looks good, i will see if i can help with that...

**Comment by shinae-woo** [comment]
@GalSagie PR #663 introduce a new module test framework. Hope this will help.
