### ISSUE TITLE
tcpdump gives segmentation fault when using wrong module name

### ISSUE THREAD

**Issue by GalSagie** [NetSys/bess#493]
Log attached: working on fixing this

F0601 10:55:18.417379 55718 debug.cc:359] A critical error has occured. Aborting...
Signal: 11 (Segmentation fault), si_code: 1 (SEGV_MAPERR: address not mapped to object)
pid: 55703, tid: 55718, address: 0x90, IP: 0x67fa10
Backtrace (recent calls first) ---
(0): ./bin/bessd() [0x67fa10]
    enable_hook_for_module(Module const*, unsigned short, bool, bool, bess::GateHookFactory const&, google::protobuf::Any const&) [clone .constprop.513] at /home/gsagie/bess/core/bessctl.cc:118
         115:       }
         116:     }
         117:   } else {
      -> 118:     for (auto& gate : m->ogates()) {
         119:       if (!gate) {
         120:         continue;
         121:       }
(1): ./bin/bessd(_ZN15BESSControlImpl17ConfigureGateHookEPN4grpc13ServerContextEPKN4bess2pb24ConfigureGateHookRequestEPNS4_15CommandResponseE+0x14c) [0x67fe8c]
    BESSControlImpl::ConfigureGateHook(grpc::ServerContext*, bess::pb::ConfigureGateHookRequest const*, bess::pb::CommandResponse*) at /home/gsagie/bess/core/bessctl.cc:1334
      -> 1334:           enable_hook_for_module(it->second, gate_idx, is_igate, use_gate,
(2): ./bin/bessd(_ZNSt17_Function_handlerIFN4grpc6StatusEPN4bess2pb11BESSControl7ServiceEPNS0_13ServerContextEPKNS3_24ConfigureGateHookRequestEPNS3_15CommandResponseEESt7_Mem_fnIMS5_FS1_S8_SB_SD_EEE9_M_invokeERKSt9_Any_dataOS6_OS8_OSB_OSD_+0x47) [0x6d67c7]
    grpc::Status std::_Mem_fn_base<grpc::Status (bess::pb::BESSControl::Service::*)(grpc::ServerContext*, bess::pb::ConfigureGateHookRequest const*, bess::pb::CommandResponse*), true>::operator()<grpc::ServerContext*, bess::pb::ConfigureGateHookRequest const*, bess::pb::CommandResponse*, void>(bess::pb::BESSControl::Service*, grpc::ServerContext*&&, bess::pb::ConfigureGateHookRequest const*&&, bess::pb::CommandResponse*&&) const at /usr/include/c++/5/functional:600
      -> 600: 	{ return (__object->*_M_pmf)(std::forward<_Args>(__args)...); }
     (inlined by) std::_Function_handler<grpc::Status (bess::pb::BESSControl::Service*, grpc::ServerContext*, bess::pb::ConfigureGateHookRequest const*, bess::pb::CommandResponse*), std::_Mem_fn<grpc::Status (bess::pb::BESSControl::Service::*)(grpc::ServerContext*, bess::pb::ConfigureGateHookRequest const*, bess::pb::CommandResponse*)> >::_M_invoke(std::_Any_data const&, bess::pb::BESSControl::Service*&&, grpc::ServerContext*&&, bess::pb::ConfigureGateHookRequest const*&&, bess::pb::CommandResponse*&&) at /usr/include/c++/5/functional:1857
      -> 1857: 	    std::forward<_ArgTypes>(__args)...);
(3): ./bin/bessd(_ZN4grpc16RpcMethodHandlerIN4bess2pb11BESSControl7ServiceENS2_24ConfigureGateHookRequestENS2_15CommandResponseEE10RunHandlerERKNS_13MethodHandler16HandlerParameterE+0xb1) [0x6f46f1]
    std::function<grpc::Status (bess::pb::BESSControl::Service*, grpc::ServerContext*, bess::pb::ConfigureGateHookRequest const*, bess::pb::CommandResponse*)>::operator()(bess::pb::BESSControl::Service*, grpc::ServerContext*, bess::pb::ConfigureGateHookRequest const*, bess::pb::CommandResponse*) const at /usr/include/c++/5/functional:2267
      -> 2267:       return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
     (inlined by) grpc::RpcMethodHandler<bess::pb::BESSControl::Service, bess::pb::ConfigureGateHookRequest, bess::pb::CommandResponse>::RunHandler(grpc::MethodHandler::HandlerParameter const&) at /usr/local/include/grpc++/impl/codegen/method_handler_impl.h:59
      -> 59:       status = func_(service_, param.server_context, &req, &rsp);
(4): ./bin/bessd(_ZN4grpc6Server24SyncRequestThreadManager6DoWorkEPvb+0x898) [0xa06dd8]
    grpc::Server::SyncRequestThreadManager::DoWork(void*, bool) at ??:?
(5): ./bin/bessd(_ZN4grpc13ThreadManager12MainWorkLoopEv+0xc6) [0xa09106]
    grpc::ThreadManager::MainWorkLoop() at ??:?
(6): ./bin/bessd(_ZN4grpc13ThreadManager12WorkerThread3RunEv+0xb) [0xa0916b]
    grpc::ThreadManager::WorkerThread::Run() at ??:?
(7): ./bin/bessd() [0xc6630f]
    execute_native_thread_routine at thread.o:?
(8): /lib/x86_64-linux-gnu/libpthread.so.0(+0x76b9) [0x7f0b923926b9]
    start_thread at ??:?
(9): /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7f0b920c882c]
    clone at /build/glibc-9tT8Do/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by GalSagie** [comment]
Found the cause, tcpdump on unknown module name gives this segmentation

**Comment by GalSagie** [comment]
Found and fixed the issue in pull request #496 and just added another safety check in the python API in #495

**Comment by sangjinhan** [comment]
Thank you for the patch.
