### ISSUE TITLE
Multi-NIC phy-to-phy software switch

### ISSUE THREAD

**Issue by llvilanova** [NetSys/bess#516]
Sorry if an issue is not the place to raise this question, but I couldn't find a mailing-list.

I was just wondering if I could use BESS as a substitute to Lagopus [1,2], and if you have any intuition (or even numbers!) of how it would compare performance-wise.

Thanks a lot!

[1] http://www.lagopus.org/
[2] https://www.slideshare.net/lagopus/dpdk-summit-2015-its-kind-of-fun-to-do-the-impossible-with-dpdk

**Comment by sangjinhan** [comment]
Given that BESS does not have any pre-built packet processing pipeline, its performance will entirely depend on what you would like to do in the datapath and how you configure it. The single-core throughput could be as high as 50Mpps (just doing simple patch panel) or as low as a couple of Mpps (if there are complex lookups or heavy packet manipulations).

I don't know much about the performance of Lagopus, but I think it probably is not a good idea to use BESS as a drop-in replacement of Lagopus, if your workload is heavily OpenFlow-oriented. If you can give me some more details on what you want your switch to perform, I can make some educated guesses for ballpark performance estimation...

**Comment by llvilanova** [comment]
We're not very focused on openflow, but rather on performing regular learning switch operations *and* packet/flow load-balancing using some application-specific knowledge.

What lagopus does is parallelize packet processing using multiple cores (page 17 in [1]), and it seems we could do the same with BESS too (by instantiating a packet-processing module multiple times). The performance of lagopus is shown in page 21 of [1]; they get line-rate performance for a simple learning switch with 4 10Gb NICs (aggregate line-rate is 40Gb) and an 8-core CPU when processing 1K packets (300B packets when using a NIC+FPGA).

[1] https://www.slideshare.net/lagopus/dpdk-summit-2015-its-kind-of-fun-to-do-the-impossible-with-dpdk

**Comment by sangjinhan** [comment]
For the MAC-learning switch scenario alone , I think 2-3 cores should be enough to handle 40Gbps traffic with minimum-sized packets. Application-layer LB would add some overheads, but I guess total 4 cores will do the job, assuming the LB operation is simple and stateless.

Parallelization in BESS can be done via replication (each core has its own datapath) or pipelining (the datapath is broken into multiple stages across cores), or combination of those two.

One thing you need to keep in mind is, though, that BESS it not a ready-to-use vswitch. It is rather a framework for 'build your own vswitch', which means that you will need to do some amount of programming. You can start by writing a simple BESS configuration script for development and test, but once you want something more than static configuration, you will need to write a controller in Python that instantiates and configures BESS modules at runtime.
