### ISSUE TITLE
how to write a new module? 

### ISSUE THREAD

**Issue by zhangwei1984** [NetSys/bess#558]
If we want to add a new  module, what steps should we follow? 

In core directory, XXpbXX.h and XXpbXX.cc are generated automatically.  Every module has some related information in those files.   If we want to add a new module, where should we modify and then it can generate related information? 

Eg: HashLB module has related information inside  module_msg.pb.h and module_msg.pb.cc.  If a new module named Foo, where should we change, then the related information can be added into those files?  Or could the group write a wiki bog, then we can follow it?

**Comment by changlan** [comment]
You are not expected to change `*.pb.[cc|h]` files. Those files are generated by Protobuf compiler from `*.proto` files. In general, writing a custom module is very simple:

1. Add new message types in `protobuf/module_msg.proto` if your module needs them.
2. Define and implement your module in `core/modules/[new_module].[cc|h]`. The module class should inherit `Module` and `ADD_MODULE` should be called in the `cc` file.

For more information about the mechanics of BESS modules, please refer to https://github.com/NetSys/bess/wiki/Deep-Dive-into-BESS-Modules.

**Comment by zhangwei1984** [comment]
thanks! my problem gets solved.
