### ISSUE TITLE
scheduler constraints

### ISSUE THREAD

**Issue by muraliran** [NetSys/bess#561]
Can we have a brief doc on how the scheduler constraints work on numa system? This is o/p on twin socket & 32 core system. I get similar errors in my scripts definig custom datapaths, so need to understand how constraints work.

```
localhost:10514 $ run muralir/multicore-phy
Done.
Placement violations found
name !leaf_src0:0 allowed_sockets [1] worker_socket 0 worker_core 0
name !leaf_src1:0 allowed_sockets [1] worker_socket 0 worker_core 1
constraints violated for module port_out0 -- please check bessd log
constraints violated for module src0 -- please check bessd log
constraints violated for module src1 -- please check bessd log
```

**Comment by sangjinhan** [comment]
There are two types of placement violation; hard and soft. The former is about potential race conditions (thus affecting correctness). The latter is not really a hard failure, but a performance hint. Your case looks like a soft violation.

I guess your physical NIC interface is connected to socket 1, but the workers are on core 0 and 1, which are on socket 0. Try launching workers on core 16 and 17, if they belong to socket 1, like this: `bess.add_worker(wid=0, core=16)`
