### ISSUE TITLE
BESS under LXD

### ISSUE THREAD

**Issue by mrb1090** [NetSys/bess#598]
Curious if anyone has run BESS within an LXD/LXC container?  If so, pointers on how to would be greatly appreciated.

Thanks,

Mike B.

**Comment by sangjinhan** [comment]
I don't know much about LXD/LXC... Haven't tried it before, but it seems to work with the following commands:

```
$ lxc launch ubuntu: --ephemeral bess-container -c security.privileged=true
$ lxc config device add bess-container bessdir disk path=/opt/bess source=/home/sangjin/bess
$ lxc exec bess-container bash
root@bess-container:~# /opt/bess/core/bessd -f
I0731 18:19:12.615233   447 main.cc:62] Launching BESS daemon in process mode...
...
```

Feel free to reopen this issue if you have any follow-up questions.

**Comment by mrb1090** [comment]
Thanks Sangjin...

Mike B
