### ISSUE TITLE
How to implement an asynchronous offload module

### ISSUE THREAD

**Issue by llvilanova** [NetSys/bess#608]
Hi! Just for fun (and to get to know BESS) I'm implementing two new modules for a learning switch:

* LearnerL2Port: keeps track of source MACs passing through some port, tells LearnerL2Bcast about new ones
* LearnerL2Bcast: receives info from multiple LearnerL2Port instances, and broadcasts it to L2Forward

The idea is to have a `LearnerL2Port` instance as early as possible on the pipeline to sniff for new source MACs on a port. If a new MAC is found, queue "something" into a central `LearnerL2Bcast` instance, which will (somehow) inform all L2Forward instances (which can be anywhere on the pipeline, in my case at the very end).

Example pipeline:

<pre>
QueueInc1 -> LearnerL2Port1 -> ... processing ... -> L2Forward1 -> QueueOut1..2 (depends on rule)
                        v                                ^
             LearnerL2Bcast ..............................
                        ^                                v
QueueInc2 -> LearnerL2Port2 -> ... processing ... -> L2Forward2 -> QueueOut1..2 (depends on rule)
</pre>

Does this even make sense? (I *think* I'll need something similar but with more complicated logic in the future) If so, how do I write a `LearnerL2Bcast` module that runs on a separate worker thread, and make other workers "push" some fake packages / messages to it? And then how do I invoke the `add()` command on each `L2Forward` instace from the single `LearnerL2Bcast`? (if that's the proper thing to do).

I'm aware that I could use a system-wide `L2Forward`, and modify it to have a per-worker cache of src MACs (this only works if we assume each port is on a separate worker), used to update the per-instance routing table (protected by a lock).

I just wanted a way to experiment with new setups and the possibilities in BESS (like splitting a pipeline between multiple workers) that might make sense in the future for my target.

**Comment by sangjinhan** [comment]
As far as MAC-learning switch is concerned, I would approach a little bit differently. The datapath is completely passive, and learning is done by an external controller out-of-band. Something like:

```
                             (matched)         ->
        PortInc  ->  ExactMatch ->  L2Forward  ->  PortOut
      (from NICs)          |                   -> (to NICs) 
                           |                         ^
            default gate   |                         |           
              (unmatched)  |                     Replicate (for flooding)
                           |                         ^
                           v                         |
                        PortOut                   PortInc
                      (To/from controller with UnixSocket)
```

`ExactMatch` contains all "known" MAC addresses and redirect all packets with an unknown source MAC address to the controller. `L2Forward` has the same set of MAC addresses for destination MAC address matching. The controller is a small Python program, which reads packets from the socket, add entries to both `ExactMatch` and `L2Forward`. Then return the packet back to the BESS datapath for flooding. This approach is quite similar to how OpenFlow switches implement L2 learning.

The reason I would prefer out-of-band over in-band is that it can avoid all the potential troubles you mentioned: thread safety, how to locate and send commands to other modules, asynchrony, etc. `ExactMatch` and `L2Forward` are thread-safe for dataplane operations (they are read-only), so any synchronization such as locks will be needed only when there are new MAC addresses.

Also note that when you forward packets to controller, you also need to tag the packet with its input port. There are a couple of ways to do it: e.g., using `SetMetadata`+`GenericEncap` to embed input port ID to the packet, creating a controller port for each data port, etc.

**Comment by sangjinhan** [comment]
One obvious drawback of this out-of-band approach would be control-plane performance. But I wouldn't care much unless I need to process 100s of thousands of new MAC addresses per second...

**Comment by llvilanova** [comment]
Interesting, I didn't think about calling out to an external program. I have two questions about this setup:

* Why use `ExactMatch` + `L2Forward`? Isn't it enough to have only `L2Forward` and send all unmatched MACs to the external controller? (by setting the default gate)

* Is there any example external controller to see how to receive/process/send packets (with metadata), and how to invoke a module's method? (I guess I need to invoke `L2Forward.add()` from my external controller)

**Comment by sangjinhan** [comment]
1. L2Forward looks at the destination MAC address of the packet for switching. But MAC learning is done with the _source_ MAC address. This is why you'd need an ExactMatch module to check if a packet has an unknown source IP address.

2.1. There is no direct support from PortInc/QueueInc/PortOut/QueueOut modules for metadata exchange (only raw packet data will be transferred). This is why I suggested the `SetMetadata` + `GenericEncap` combo to explicitly encapsulate each packet with its metadata.

2.2. External controllers can invoke commands to modules as defined. See `bessctl/conf/samples/l2forward` as an example. If you want to do it outside a BESS script (let's say, your standalone Python controller), unfortunately the interface is less convenient at the moment; you would need to call pybess.run_module_command(<module name, e.g., `l2_forward0`>, <command name, e.g., `add`>, ...). See `pybess/module.py` and `pybess/bess.py`. I need to make the API more user friendly...

**Comment by llvilanova** [comment]
True, so silly me, thanks a lot! :)

You can close the issue if you want.
