### ISSUE TITLE
Break pipeline into multiple workers

### ISSUE THREAD

**Issue by llvilanova** [NetSys/bess#610]
Do you have any pointers about how to split my pipeline into multiple stages on different workers? (to actually pipeline packet processing and reduce latency)

I've looked at the documentation and couldn't find any obvious answer.

**Comment by sangjinhan** [comment]
The `Queue` module is schedulable, so you can bind it to another worker. For (untested) example:

```
bess.add_worker(wid=0, core=2)
bess.add_worker(wid=1, core=3)

a::PortInc -> B -> q::Queue -> C -> PortOut
a.attach_task(wid=0)
q.attach_tack(wid=1)
```

then a -> B -> q will run on core 2, and q -> C -> PortOut will run on core 3. You can grep `add_tc`, `attach_task`, `add_worker`, and `Queue` in the `bessctl/conf/` directory for usage examples. Sorry about the (lack of) documentation.

**Comment by llvilanova** [comment]
Works like a charm, thanks.

Just to be sure after looking at the code, if I don't set `backpressure`, a queue overflow will simply drop packets, whereas setting `backpressure` will make sure the port - indirectly - feeding that queue (e.g, `PortInc`) won't be scheduled until an underflow is signalled (packets might still be dropped, but possibly less of them).

**Comment by llvilanova** [comment]
Response from @sangjinhan fully addresses my question. Closing.
