### ISSUE TITLE
Command "show driver <name>" does not work

### ISSUE THREAD

**Issue by llvilanova** [NetSys/bess#612]
If I run `show driver <name>` in `bessctl`, I get the following error for `show driver PMDPort` (same error for any driver, existing or not):

<pre>
*** Error: No driver 'P' found
  BESS daemon response - errno=2 (ENOENT: No such file or directory)
       query: GetDriverInfo
   query_arg: {'driver_name': 'P'}
</pre>

Looks like the name is being truncated to the first letter of the string argument somewhere.

**Comment by chris3torek** [comment]
fixed by 1b9db04 (need to figure out how to make commits auto-close issues on github)
