### ISSUE TITLE
build.py errors from pb

### ISSUE THREAD

**Issue by muraliran** [NetSys/bess#617]
I merged master after a month and seem to get this error

[CXX]       dpdk.o
bess_msg.pb.cc:1219:48: error: unused parameter ‘output’ [-Werror=unused-parameter]
     ::google::protobuf::io::CodedOutputStream* output) const {

Noticed the c++11 and gcc 6 support added for grpc. Even re-installing packages.yml is not fixing. Am I missing something?

**Comment by chris3torek** [comment]
The generated grpc code (with unused parameters) is very sensitive to the specific version of grpc and plugins that are installed. I've had a lot of build issues that traced to this. We tweaked the packages.yml build rules to make sure the correct grpc and plugins get built: you need to have tag `v1.3.2` checked out, do the submodule updates, and then run `make` with `HAS_SYSTEM_PROTOBUF=false` and install everything.

Not sure that's the actual problem, but it's the one I kept hitting, anyway...

**Comment by muraliran** [comment]
Going through the list of changes again, I think I got the issue. The pb code was moved to core/pb/ But old generated files were in core and conflicting. Deleted all core/*pb* and built fine. 
Sorry - I should have waited a bit more before raising issue :)

**Comment by muraliran** [comment]
meant generated files in core. That is core/\*pb\* - formating made it italics
