### ISSUE TITLE
"undefined reference to '__dlopen'" in [TEST_LD]gate_test of building ''Daemon"

### ISSUE THREAD

**Issue by tianfengfrank** [NetSys/bess#631]
When building Daemon in [TEST_LD]gate_test process, it shows "undefined reference to '__dlopen'".
My OS is Ubuntu 16.04 LTS.

**Comment by tianfengfrank** [comment]
#

**Comment by sangjinhan** [comment]
I think this issue was addressed in #626 (also see #618). If you update the repository and do (preferably clean) rebuild, everything should be fine. Please let me know if not.
