### ISSUE TITLE
Cannot call command on a 3rd-party plugin's module (argument type not known)

### ISSUE THREAD

**Issue by llvilanova** [NetSys/bess#652]
I have an external library, loaded with `import plugin`. Whenever I call a command for one of my modules on a bess script it fails complaining the arg type is unknown:

<pre>
*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/home/lluis/Projects/dos.experiments/src/switch/switch.bess", line 104, in <module>
    mcs.add_node(ip="10.0.16.1")
  File "/home/lluis/Projects/dos.experiments/deps/bess/bessctl/../pybess/module.py", line 37, in <lambda>
    self.bess.run_module_command(self.name, cmd, arg_type, kwargs)
  File "/home/lluis/Projects/dos.experiments/deps/bess/bessctl/../pybess/bess.py", line 445, in run_module_command
    raise self.APIError('Unknown arg "%s"' % arg_type)
APIError: Unknown arg "MCSCommandAddNodeArg"
  Command failed: run file /home/lluis/Projects/dos.experiments/src/switch/switch.bess
</pre>

**Comment by llvilanova** [comment]
Aha! Thanks. I was trying to build it a bit differently from an external directory by sourcing `core/bess_plugin.mk` (to avoid modifying the bess clone) and forgot to depend on the python rules.

**Comment by chris3torek** [comment]
FYI, there's a new procedure for building a whole raft of extra plugins without modifying clones: use `./build.py --plugin <dir> show-plugins` to add `<dir>` as a source of `protobuf/` and `modules/` directories (same layout as bess). Once you have added a plugin it remains in the list, and `show-plugins` just serves as a sort of no-op command to verify that it's in there (so you can add more at any time, or reset everything away with `--reset-plugins`).
