### ISSUE TITLE
Unfreed `bess::Packet` objects are reused

### ISSUE THREAD

**Issue by llvilanova** [NetSys/bess#659]
I have a module that processes packet batches and in certain cases temporarily stows away some of these packet objects (`bess::Packet`), and eventually sends them to the next module. After debugging, it looks like the input packet batches contain packet pointers that are the same as those I stowed away (i.e., my module were never passed them on a batch to `RunNextModule`, nor called `bess::Packet::Free`.

Is this the expected behaviour? If so, what should I use to temporarily delay some packets? (I tried `bess::Packet::copy`, but these packet buffers are also reused by BESS without my module knowing it).

**Comment by shinae-woo** [comment]
No, buffering packets should correctly work, if you don't pass them to the next modules. Could you please share your source code how to buffer packets? It makes easier to figure out.
