### ISSUE TITLE
Support for newer kernel versions

### ISSUE THREAD

**Issue by rware** [NetSys/bess#671]
BESS works best under kernel version 4.4, but are there plans to support newer kernel versions? Specifically, I've tried BESS on kernel version 4.9 and couldn't get it to work. For context, my topology consisted of two docker VPorts connected to each other like the example here: https://github.com/NetSys/bess/wiki/Hooking-up-BESS-Ports#connecting-vms-and-containers-with-bess-vports

**Comment by sangjinhan** [comment]
Hi Ray, is it a build issue, or something else? If kernel module fails to build on newer kernel versions, please update the repo to the latest version; @changlan recently made a fix to support 4.11+ (#657). If the module builds okay but you find some run-time issues on newer kernels, please let me know (I haven't tried new kernels myself yet).

**Comment by rware** [comment]
Whelp, I updated my repo and tried building it again, but this time on the latest stable kernel version 4.13 and now it seems to work fine.
