### ISSUE TITLE
Questions about BESS internals

### ISSUE THREAD

**Issue by h0ax-ki1l3r** [NetSys/bess#672]
Hi,

I am trying to understand the internals of BESS. Could someone please help answer the following questions and if possible point where in the code can I go to understand the pieces.

1. What happens to the unused attributes, or ones that will no longer be used in the pipeline? Are they freed, if yes where can I find this logic in your source code?

2. How is the memory reclaimed? Can someone shed some more light on how the shared buffer is accessed and allocated in BESS? 

3. If certain configurations to the pipeline are made during runtime, what happens to the packets that are already in the pipeline and are being processed? Can changes to the pipeline only be made when there are no packets being processed?

Thanks!

**Comment by sangjinhan** [comment]
1. They are not explicitly "freed", but the space used for those attributes can be reclaimed and overwritten for other attributes by downstream modules. Please take a look at `metadata.cc/h` files. I attached some slides as well.
[BESS_metadata.pptx](https://github.com/NetSys/bess/files/1376696/BESS_metadata.pptx)

2. I am afraid I don't understand what you mean by memory or shared buffer. If you are wondering about where the metadata attributes are stored, they are per-packet, so each packet buffer (class Packet) has space to store them.

3. Conceptually, there are 1 master thread (for configuration) and N worker threads (for actual packet processing). When some changes are being made, the master thread will make sure that all worker threads are done with any in-flight packets. This is done via `ResumeAll` or `WorkerPauser`.

**Comment by h0ax-ki1l3r** [comment]
Thanks for that quick response!

1a) Slide 12: "Each packet buffer reserves 96B for dynamic metadata."  If BESS reserves 96B for metadata, what if there is no need 96B of per-packet metadata anywhere in the pipeline, do you think that is a potential limitation? If not, please help me understand.  "Note: size doesn’t matter, since no initialization is required" I am a little confused about what "size" here means, do you mean size of the individual attributes or size of the entire metadata block?

1b) Slide 13, what does N/A here mean? Is it used by BESS to annotate unused attributes in downstream?

1c) Slide 14/15, how do you define a maximal subgraph and how do yo determine one? My understanding is- along a fixed deterministic path, if the same attribute was overwritten (e.g. modules that does w:A the gray-colored subgraph) by some module that causes to create another subgraph.

1c) Graph coloring and maximal graph idea is interesting! I am assuming BESS does the graph coloring process (or deciding of attribute offsets) during compile time and then at runtime (if changes are made)? 

Thanks once again!

**Comment by chris3torek** [comment]
re question 1a: if some of the 96 bytes go unused, they could be considered wasted space.  But note that 96 is 3 x 32 = 3 cache lines.  The number of bytes should be a multiple of the cache line size for performance reasons in the part of the dataplane that doesn't use the metadata.

1b: I don't see "N/A" on slide 13...

1c: scope and maximal subgraph here are the same as they are in compilers doing variable lifetime analysis.  A variable becomes live when written, and is dead when written again (the new write produces a new variable). Compare with static single assignment, https://en.wikipedia.org/wiki/Static_single_assignment_form.  For your repeated 1c 😸 the attribute computation occurs at runtime when building the graph (though I'm not enough of a BESS guru to say whether there's code to re-use an earlier subgraph computation).

**Comment by h0ax-ki1l3r** [comment]
Got it. Thanks Sangjin and Chris!
