### ISSUE TITLE
Bug in IPLookup() and a possible fix

### ISSUE THREAD

**Issue by nemethf** [NetSys/bess#678]
It seems the IPLookup module doesn't work correctly if the size of the batch it receives is not divisible by 4.

I tried to write a test case in the new testing framework but then iplookup always failed for me.  Anyway, the problem can be demonstrated with the following bess script:
```python
from test_utils import *
import time

burst = int($BURST!'4')
pkt_udp = get_udp_packet(sip='172.12.0.3', dip='127.12.0.4')
rwtemp = [bytes(pkt_udp)]

q = Queue()
q.set_burst(burst=burst)

iplookup = IPLookup(name='ip')

iplookup.add(prefix='0.0.0.0', prefix_len=0, gate=0)
iplookup.add(prefix='127.0.0.0', prefix_len=8, gate=1)

Source() -> Rewrite(templates=rwtemp) -> q -> iplookup

iplookup:0 -> Sink()
iplookup:1 -> Sink()

bess.resume_all()
time.sleep(1)
bess.pause_all()
info = bess.get_module_info('ip')
print('%2d | %8d | %8d' % (burst, info.ogates[0].pkts, info.ogates[1].pkts))
``` 
And this is what I get with different `burst` values:
(In the the bug-free case, the second column should contain only zeros)

burst | #pkt -- ogate 0 | #pkt -- ogate 1 
------ | --------------------- | -------------
 1 |  1535615 |        0
 2 |  3131646 |        0
 3 |  4425213 |        0
 4 |        0 |  5556732
 5 |  1433727 |  5734908
 6 |  2857214 |  5714428
 7 |  4173693 |  5564924
 8 |        0 | 10580984
 9 |  1419647 | 11357176
... | ... | ... |

The following patch fixes the issue for me.  Shall I send it as a pull request?
```
diff --git a/core/modules/ip_lookup.cc b/core/modules/ip_lookup.cc
index d93248cf..6c50a9c6 100644
--- a/core/modules/ip_lookup.cc
+++ b/core/modules/ip_lookup.cc
@@ -30,6 +30,8 @@
 
 #include "ip_lookup.h"
 
+#include <netinet/in.h>
+
 #include <rte_config.h>
 #include <rte_errno.h>
 #include <rte_lpm.h>
@@ -239,7 +241,7 @@ void IPLookup::ProcessBatch(bess::PacketBatch *batch) {
     eth = batch->pkts()[i]->head_data<Ethernet *>();
     ip = (Ipv4 *)(eth + 1);
 
-    ret = rte_lpm_lookup(lpm_, ip->dst.raw_value(), &next_hop);
+    ret = rte_lpm_lookup(lpm_, ntohl(ip->dst.raw_value()), &next_hop);
 
     if (ret == 0) {
       out_gates[i] = next_hop;
```

**Comment by sangjinhan** [comment]
Thank you for reporting the issue! A fix has been made.
