### ISSUE TITLE
No such device ERROR when running port/latency and port/vxlan samples

### ISSUE THREAD

**Issue by zylan29** [NetSys/bess#698]
Hi,

When I try to run the port/latency and port/vxlan samples, BESS daemon reports 
the kernel module is not loaded and No such device ERROR:
```
localhost:10514 $ run port/latency
*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/home/zylan29/bess/bessctl/conf/port/latency.bess", line 6, in <module>
    v = VPort(loopback=1, rxq_cpus=[1])
  File "/home/zylan29/bess/bessctl/../pybess/port.py", line 12, in __init__
    self.choose_arg(None, kwargs))
  File "/home/zylan29/bess/bessctl/../pybess/bess.py", line 270, in create_port
    return self._request('CreatePort', request)
  File "/home/zylan29/bess/bessctl/../pybess/bess.py", line 158, in _request
    raise self.Error(code, errmsg, query=name, query_arg=req_dict)
*** Error: the kernel module is not loaded
  BESS daemon response - errno=19 (ENODEV: No such device)
       query: CreatePort
   query_arg: {'driver': 'VPort', 'arg': {'type_url': 'type.googleapis.com/bess.pb.VPortArg', 'value': '*\x01\x01@\x01'}}
```

The OS is ubuntu 16.04 VM, and the kernel is igb_uio. One virual NIC is binded to DPDK by using igb_uio.
```
sudo bin/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:02:06.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' if=ens33 drv=e1000 unused=igb_uio *Active*
```

igb_uio seems to be a valid dpdk driver. Is this sample not runnable in virtual machines? Am I missing something here?

Furthermore, I cannot bind NIC by using uio_pci_generic in my VM, so I use igb_uio instead, is it the problem?

**Comment by sangjinhan** [comment]
Those `port/latency` and `port/vxlan` examples work with kernel network interfaces created by the BESS kernel module (you can think of it as TUN/TAP devices). They should work in a VM. The examples just "create" devices, and the whole process is completely independent from DPDK. You don't need actual (whether they are physical or virtual) devices at all.

To run those examples you need the kernel module (`core/kmod/bess.ko`). You can build it with`./build.py kmod`. For this you will need `linux-headers-*` package installed.

**Comment by zylan29** [comment]
@sangjinhan
It works! Thanks.
