### ISSUE TITLE
Mellanox ConnectX-3 not detected

### ISSUE THREAD

**Issue by pchaigno** [NetSys/bess#699]
BESS doesn't detect my Mellanox ConnectX-3 Pro device.
I'm using the x86_64 binary from the 0.3.0 release.

The device is correctly detected by DPDK if I compile DPDK from sources with OFED (I'm already using it with OVS-DPDK). BESS also correctly detects the second device (Intel) if I switch its driver to `uio_pci_generic`. Only the Mellanox device is not detected by BESS.

```
$ ./bin/bessd -f -k -v=2
[...]
I1024 13:57:14.385973  5290 dpdk.cc:58] EAL: Probing VFIO support...
I1024 13:57:16.584007  5290 dpdk.cc:58] EAL: PCI device 0000:00:19.0 on NUMA socket 0
I1024 13:57:16.584080  5290 dpdk.cc:58] EAL:   probe driver: 8086:15a0 net_e1000_em
I1024 13:57:16.832849  5290 packet.cc:71] Allocating 262143 buffers on socket 0: OK
I1024 13:57:16.991312  5290 packet.cc:71] Allocating 262143 buffers on socket 1: OK
I1024 13:57:16.991380  5290 pmd.cc:46] 0 DPDK PMD ports have been recognized:
I1024 13:57:16.991407  5290 vport.cc:284] vport: BESS kernel module is not loaded. Loading...
I1024 13:57:16.996976  5290 bessctl.cc:1602] Server listening on 127.0.0.1:10514

$ ibstat
CA 'mlx4_0'
	CA type: MT4103
	Number of ports: 2
	Firmware version: 2.40.7000
	Hardware version: 0
        [...]
```

Could it be that something is missing for the binary release?

**Comment by sangjinhan** [comment]
You are right, the binary release does not support ConnectX-3/4 drivers. They are enabled only when bess is built from source, and required dependency packages are available. I am not sure if it still is the case, but in the past the DPDK PMD drivers needed some Mellanox proprietary software that we cannot include in our build process.

**Comment by pchaigno** [comment]
Thanks for the quick answer.
I haven't had much success compiling from sources. I'll try again on a clean setup.

> I am not sure if it still is the case, but in the past the DPDK PMD drivers needed some Mellanox proprietary software that we cannot include in our build process.

Still the case.
