### ISSUE TITLE
ExactMatch sometimes routing matching packets to default gate

### ISSUE THREAD

**Issue by Codeacious** [NetSys/bess#702]
Hello,

When using the built-in ExactMatch module, I'm sometimes seeing packets being routed to the default gate, even when they match an added rule.

Here's a simple test that exhibits this behavior:
```
import scapy.all as scapy
import socket

pkt_size = int($BESS_PKT_SIZE!'1500')
assert(60 <= pkt_size <= 1500)

def aton(ip):
    return socket.inet_aton(ip)

def gen_packet(proto, src_mac, dst_mac, src_ip, dst_ip):
    eth = scapy.Ether(src=src_mac, dst=dst_mac)
    ip = scapy.IP(src=src_ip, dst=dst_ip)
    pro = proto(sport=scapy.RandShort(), dport=scapy.RandShort())
    payload = ('cat' * 500)[:pkt_size-len(eth/ip/pro)]
    pkt = eth/ip/pro/payload
    return bytes(pkt)

src_ip = str(scapy.RandIP())
dst_ip = str(scapy.RandIP())
packets = [gen_packet(scapy.UDP,
                      scapy.RandMAC(), scapy.RandMAC(),
                      src_ip, dst_ip)]

em_out = ExactMatch(fields=[{'offset':23, 'num_bytes':1},
                            {'offset':26, 'num_bytes':4},
                            {'offset':30, 'num_bytes':4}])
em_out:1 -> Sink(name="dead_pkts")
em_out.set_default_gate(gate=1)

Source(pkt_size=pkt_size) -> Rewrite(templates=packets) -> em_out
em_out.add(fields=[{'value_int':17},
                   {'value_bin':aton(src_ip)},
                   {'value_bin':aton(dst_ip)}])
em_out:0 -> Sink(name="good_pkts")
```

When running this, I see packets routed to both sinks, instead of just the `"good_pkts"` sink as expected:

```
localhost:10514 $ show module em0
  em0::ExactMatch(3 fields, 1 rules)
    Input gates:
          0: batches 0                packets 0                rewrite0:0 ->
    Output gates:
          0: batches 1205874          packets 34970346         -> 0:good_pkts
          1: batches 1205874          packets 3617622          -> 0:dead_pkts
```

Using the `tcpdump` command in `bessctl` shows (from what I can tell) that the outbound packets on both gates are the same.

```
tcpdump em0 out 0 -n -x -K
...
0x0000:  4500 05ce 0001 0000 4011 abee 5248 4375
0x0010:  4ed3 e49f fcbd b34b 05ba 29ef 6361 7463
0x0020:  6174 6361 7463 6174 6361 7463 6174 6361
...

tcpdump em0 out 1 -n -x -K
...
0x0000:  4500 05ce 0001 0000 4011 abee 5248 4375
0x0010:  4ed3 e49f fcbd b34b 05ba 29ef 6361 7463
0x0020:  6174 6361 7463 6174 6361 7463 6174 6361
...
```

**Comment by chris3torek** [comment]
I'm guessing a bit here but I suspect you have not paused the BESS threads when you are setting up your exact match instance (there's no pause/resume above).  Your example connects these up first:

    Source(pkt_size=pkt_size) -> Rewrite(templates=packets) -> em_out

and only then adds the matcher to route UDP packets with the source and destination ports:

    em_out.add(fields=[{'value_int':17},
                       {'value_bin':aton(src_ip)},
                       {'value_bin':aton(dst_ip)}])

Between the first and second, a bunch of packets go to the default gate.

**Comment by Codeacious** [comment]
Thank you for pointing that out; I assumed bessctl paused all threads until the script was finished due to the call to `cli.bess.resume_all()` at the end of `_do_run_file()` in commands.py.

However, the example above has the number of packets in both cases increase consistently as it is run. Moving the add command above the Source -> Rewrite line (so the task isn't created until the rule is in place) shows the same behavior:

```
localhost:10514 $ show module em0
  em0::ExactMatch(3 fields, 1 rules)
    Input gates:
          0: batches 0                packets 0                rewrite0:0 ->
    Output gates:
          0: batches 1867821          packets 41092062         -> 0:good_pkts
          1: batches 1867820          packets 18678200         -> 0:dead_pkts
localhost:10514 $ show module em0
  em0::ExactMatch(3 fields, 1 rules)
    Input gates:
          0: batches 0                packets 0                rewrite0:0 ->
    Output gates:
          0: batches 129194391        packets 2842276602       -> 0:good_pkts
          1: batches 129194391        packets 1291943910       -> 0:dead_pkts
```

**Comment by sangjinhan** [comment]
Confirmed. Thank you for reporting. It seems that #666 introduced this issue. Commit f96a794 (just before merge) works fine, while 16295a4 (the merge commit) shows the same problem.

**Comment by chris3torek** [comment]
FYI, I found the bug and have a fix (verified with your bug tester), I'm just trying to write a small unit test that exposes the bug so that it stays fixed in the future.
