### ISSUE TITLE
Creating a pipeline with lots of Queue()s is slow

### ISSUE THREAD

**Issue by nemethf** [NetSys/bess#703]
Consider the following bess script (which is a simplified version of a real use-case.)  
```python
case = int($case!'1')

split = Split(attribute='tun_id', size=4)
ip_lookup = IPLookup()
buf = Buffer()
Source() -> split

if case == 1:
  buf -> ip_lookup

for i in range(1, 2000):
  split:i -> Queue() -> buf

for i in range(1, 250):
  ip_lookup:i -> Bypass() -> Bypass() -> Sink()

if case == 2:
  buf -> ip_lookup
```
The configuration time largely depends on how how we connect the modules: 
```
~/bess/bessctl$ time ./bessctl daemon start -- run add_edge case=1 -- daemon stop

real    3m17.908s
user    0m4.952s
sys     0m0.516s
~/bess/bessctl$ time ./bessctl daemon start -- run add_edge case=2 -- daemon stop

real    0m19.026s
user    0m4.424s
sys     0m0.532s
```

I think the slowness comes from the fact that ModuleGraph::AddEdge updates the whole task graph, but it would be enough to update only those parts of the graph that might be affected by the new edge.   With this optimization the running times decrease in both cases :
```
~/bess/bessctl$ time ./bessctl daemon start -- run add_edge case=1 -- daemon stop

real    0m9.865s
user    0m2.924s
sys     0m0.268s
~/bess/bessctl$ time ./bessctl daemon start -- run add_edge case=2 -- daemon stop

real    0m9.801s
user    0m2.900s
sys     0m0.316s
```

If my analysis is correct I can send the following patch as a pull request.  However, I think further optimizations are possible in this area.  Thanks.
 
```
diff --git a/core/module_graph.cc b/core/module_graph.cc
index d760cbf..9ce18bf 100644
--- a/core/module_graph.cc
+++ b/core/module_graph.cc
@@ -88,6 +88,21 @@ bool ModuleGraph::UpdateTaskGraph() {
   return true;
 }
 
+bool ModuleGraph::UpdateTaskSubgraph(const std::string &node_name) {
+  auto node_it = all_modules_.find(node_name);
+  if (node_it == all_modules_.end()) {
+    return false;
+  }
+  Module *node = node_it->second;
+  for (Module *it : node->parent_tasks_) {
+    std::unordered_set<std::string> visited;
+    if (!FindNextTask(it->name(), it->name(), &visited)) {
+      return false;
+    }
+  }
+  return true;
+}
+
 const std::map<std::string, Module *> &ModuleGraph::GetAllModules() {
   return all_modules_;
 }
@@ -107,7 +122,7 @@ bool ModuleGraph::AddEdge(const std::string &from, const std::string &to) {
     return false;
   }
   from_it->second.AddChild(to);
-  return UpdateTaskGraph();
+  return UpdateTaskSubgraph(from);
 }
 
 bool ModuleGraph::RemoveEdge(const std::string &from, const std::string &to) {
diff --git a/core/module_graph.h b/core/module_graph.h
index b7e6e80..65caba1 100644
--- a/core/module_graph.h
+++ b/core/module_graph.h
@@ -103,6 +103,8 @@ class ModuleGraph {
   // ignoring all modules that are not tasks.
   static bool UpdateTaskGraph();
 
+  static bool UpdateTaskSubgraph(const std::string &node_name);
+
   // Finds the next module that implements a task along the pipeline.
   // If if find any, then the current task becomes the parent of the next task.
   static bool FindNextTask(const std::string &node_name,
```

**Comment by shinae-woo** [comment]
@nemethf, Thank you so much for reporting the issue. You are correct, the updating the whole task graph every time with module connecting is too much expensive. Your idea of updating related task graph sounds really good, and I haven't figure out any side-effect on it as far as I know.

Furthermore, I actually consider one-time updating the task graph right before resuming the work. Let me have time figure out if there are any other reasons behind per module connecting updates. (I want to double check with others who knows more history than me). If there is no side-effect, I would push a patch for a resume hook for the one-time cost of updating task graph.

**Comment by nemethf** [comment]
One-time full recalculation would solve my problem perfectly. Thank you.  However, I wonder if it would still be too slow in case of a small, run-time modification of a large graph.  Or do you have something more sophisticated in your mind?

**Comment by shinae-woo** [comment]
Yes, writing whole graph would be definitely still slow. What I can do is exactly like your approach, how about accumulating changes (i.e., tasks which should be updated) and one-time update only for those?  I need to fix your code a little bit so that the changes in modules which are not tasks (they don't have parent tasks info) also triggers the updating the graphs.

Plus, there are more optimization rooms from other per-connection-changes triggered updates, (e.g., PropagateActiveWorkers()). I do not know how much overhead they have yet.

**Comment by nemethf** [comment]
The first part sounds really good to me. (I'm not familiar with PropagateActiveWorkers at all.) 
Thanks again.
