### ISSUE TITLE
HI，Bess on ubuntu14.04

### ISSUE THREAD

**Issue by btlcmr0702** [NetSys/bess#714]
hi, i want to install bess on my ubuntu 14.04 host, not VM.
But when i run the ./build.py, there is something wrong when building dpdk.

**_/home/tian/libo/bess/deps/dpdk-17.05/drivers/net/mlx5/mlx5_flow.c:969:3: error: unknown field ‘type’ specified in initializer
   .type = IBV_EXP_FLOW_SPEC_ACTION_TAG,
   ^
/home/tian/libo/bess/deps/dpdk-17.05/drivers/net/mlx5/mlx5_flow.c:969:11: error: ‘IBV_EXP_FLOW_SPEC_ACTION_TAG’ undeclared (first use in this function)
   .type = IBV_EXP_FLOW_SPEC_ACTION_TAG,
           ^
/home/tian/libo/bess/deps/dpdk-17.05/drivers/net/mlx5/mlx5_flow.c:970:3: error: unknown field ‘size’ specified in initializer
   .size = size,
   ^
/home/tian/libo/bess/deps/dpdk-17.05/drivers/net/mlx5/mlx5_flow.c:971:3: error: unknown field ‘tag_id’ specified in initializer
   .tag_id = mlx5_flow_mark_set(mark_id),
   ^
/home/tian/libo/bess/deps/dpdk-17.05/drivers/net/mlx5/mlx5_flow.c:972:2: error: invalid use of undefined type ‘struct ibv_exp_flow_spec_action_tag’
  };
  ^
/home/tian/libo/bess/deps/dpdk-17.05/drivers/net/mlx5/mlx5_flow.c: In function ‘priv_flow_create’:
/home/tian/libo/bess/deps/dpdk-17.05/drivers/net/mlx5/mlx5_flow.c:1198:25: error: invalid application of ‘sizeof’ to incomplete type ‘struct ibv_exp_flow_spec_action_tag’
   flow.offset += sizeof(struct ibv_exp_flow_spec_action_tag);
                         ^
make[4]: *** [mlx5_flow.o] Error 1
make[3]: *** [mlx5] Error 2
make[2]: *** [net] Error 2
make[1]: *** [drivers] Error 2
make: *** [all] Error 2
make: Leaving directory `/home/tian/libo/bess/deps/dpdk-17.05'**

**Error has occured running command: make -j32 -C /home/tian/libo/bess/deps/dpdk-17.05 EXTRA_CFLAGS="-g -w -fPIC"_**

Here is the part of the error message, i don't know whether to solve this, is it about ubuntu release version?I have to install bess on ubuntu 16.04?
Expect your reply.
Thank you.

**Comment by btlcmr0702** [comment]
hi
I think the error is rised by the version of DPDK doesn't match our mlnx NIC.
So i think i should change the dpdk version in build.py.
But i don't konw how to fix it.

**Comment by sangjinhan** [comment]
No, Ubuntu 14.04 should be fine. Did you install Mellanox OFED, which is a prerequisite of DPDK PMD driver for Mellanox NICs? While it seems that the latest DPDK version does not require this proprietary software (can be built with open source only), BESS does not support the newest DPDK yet. You will need to install Mellanox OFED.

**Comment by btlcmr0702** [comment]
Thanks a lot. I will try it.
