### ISSUE TITLE
Basic transmission between two hosts.

### ISSUE THREAD

**Issue by btlcmr0702** [NetSys/bess#716]
Hi, i installed BESS on my hosts. And i want to send packets from one host to the other one in our cluster.
I bind the port of  Intel 10Gb NIC  with dpdk and use FlowGen(...) -> output0 to send packets to another host which also installed BESS and binded port. Let's name these two hosts A and B.
Our cluster have 16 machines connected by a ToR switch. When i use host A to send packets to host B , all the other 14 machines will also receive the packets from A. It seems the switch broadcast the packets from A, that is very strange.
Here is the bess file:
  **_1 import scapy.all as scapy                                                         
  2 import socket
  4 myport::PMDPort(port_id=0, num_inc_q=1, num_out_q=1)
  5 input0::QueueInc(port=myport, qid=0) #This module will read from myport on queue 0
  6 output0::QueueOut(port=myport, qid=0) #This module will write to myport on queue 0
  7 
  8 eth = scapy.Ether(src='90:e2:ba:31:64:36', dst='90:e2:ba:31:64:22')
  9 ip=scapy.IP(src='192.168.9.3', dst='192.168.9.4')
 10 udp=scapy.UDP(sport=10001, dport=10002)
 11 
 12 payload = 'helloworld'
 13 pkt = eth/ip/udp/payload
 14 pkt_data = str(pkt)
 15 
 16 
 17 FlowGen(template=pkt_data, pps=1000, flow_rate = 10, flow_duration = 5.0, arrival='uniform', duration='uniform', quick_rampup=True, ip_src_range=0) -> output0_**
The mac and ip address i used in the code is the real address of two NICs, whether i need to send arp request packets first? Maybe i can find some examples for the basic transmission between hosts?
I capture the packets by tcpdump on a host(not B), the packets is correct and contains the right address. 
![qq 20171108214614](https://user-images.githubusercontent.com/19741892/32552314-7f71b32a-c4ce-11e7-9703-53ae8fccf37b.png)

Then i analyse the pcap file with wireshark.
![qq 20171104220121](https://user-images.githubusercontent.com/19741892/32551649-2c383a78-c4cc-11e7-9a25-a48a82c5a245.png)

I also use simple python script (scapy) to send packets from A and B with different NICs and other hosts will not receive packets.
Expect your reply , thanks !

**Comment by btlcmr0702** [comment]
I have solved the problem.
It sees the switch will not record the relation between port number and mac address of the NIC the port connected to.
Because the dpdk will not do the arp protocol then it broadcasts the packets, i have to reply a packet to host A from B by myself. Then the switch will know the map between port and NIC and will not broadcast packets.

**Comment by sangjinhan** [comment]
Glad you solved the issue. To work around the issue, I would recommend sending out a [Gratuitous ARP](https://wiki.wireshark.org/Gratuitous_ARP) packet at program startup on each server running BESS (or any DPDK apps).
