### ISSUE TITLE
Hi, can I generate a new packet in the middle module?

### ISSUE THREAD

**Issue by btlcmr0702** [NetSys/bess#718]
Hi, i find in all examples bess use scapy to generate a template of packet, then use rewrite or flowGen module to "generate" a packet and pass it to the downstream module.
Now i have a scenario that when i receive a packet (like a token) from other hosts, i need to send a reply to the hosts, but how can i do that in the bess? Can I just generate a new packet and fill it with my own designed parameters in the middle module ? Is there a example i can consult ?
Thank for your reply.

**Comment by chris3torek** [comment]
If you are writing your own module, you can generate your own packets.  The `core/modules/source.cc` and `core/modules/flowgen.cc` modules are of course examples of creating packets that _aren't_ replies, and there are not very many examples of creating packets that _are_ replies, but there's one I just wrote a bunch of fixes for, in `core/modules/url_filter.cc`.  See `Generate403Packet` and `GenerateResetPacket`.
