### ISSUE TITLE
How to get the payload in a packet?

### ISSUE THREAD

**Issue by btlcmr0702** [NetSys/bess#726]
I check the _**core/packet.h**_, it seems _**packet->data()**_ will return the data in packet by char*.
But when i printf the data(), the result is totally a mess， so i wonder how to get the payload in a packet? 
Thank you for your reply.

**Comment by sangjinhan** [comment]
`packet->head_data()` will give you a void pointer to the beginning of the packet payload. You can specify a type and/or an offset if you'd like, e.g., `auto *ip = packet->head_data<Ipv4 *>(14);`
