### ISSUE TITLE
Will bess drop packets when it receive the first packet?

### ISSUE THREAD

**Issue by btlcmr0702** [NetSys/bess#731]
Hi,
I find a interesting problem.
I write a module and let it just send one or two packets, and the receiver can't receive the packet, that's mean the **_Inc/RX_** will always be 0.
But if i let the module send many packets (keeping sending packets) then the receiver can receive the packets.
So i wonder will bess drop some packets at the beginning?

**Comment by sangjinhan** [comment]
No, it shouldn't drop any early packets. I recommend checking out `show pipeline` and `show port` commands, which show you accumulated stat counters (not rate as in `monitor pipeline` or `monitor port`, to figure out where packets disappear.
