### ISSUE TITLE
message.h:36:28: fatal error: pb/bess_msg.pb.h: No such file or directory

### ISSUE THREAD

**Issue by ghostli123** [NetSys/bess#750]
BESS Build Error. Not clear where to find header files under folder pb. Any hints are helpful. Thank you very much!
 
=======================================
Building BESS daemon...
Log:
 make: Entering directory '/home/ubuntu/bess/core'
[CXX]       opts.o
In file included from gate.h:40:0,
                 from worker.h:41,
                 from opts.cc:37:
message.h:36:28: fatal error: pb/bess_msg.pb.h: No such file or directory
compilation terminated.
Error: opts.o
g++ -o opts.o -c opts.cc -std=c++14 -g3 -ggdb3 -march=native -isystem /home/ubuntu/bess/deps/dpdk-17.05/build/include -isystem /home/ubuntu/bess/core -isystem ./.. -isystem /home/ubuntu/bess/core/modules -D_GNU_SOURCE -Werror -Wall -Wextra -Wcast-align -pthread -I/usr/local/include -Wshadow -fno-gnu-unique -Ofast -DNDEBUG -MT opts.o -MMD -MP -MF .deps/opts.d
Makefile:385: recipe for target 'opts.o' failed
make: *** [opts.o] Error 1
make: Leaving directory '/home/ubuntu/bess/core'

Error has occured running command: make -C core -j`nproc`
=======================================

**Comment by sangjinhan** [comment]
The error message indicates that the protobuf header files have not been generated correctly for some reason. For the first build, you will need to run `build.py`, rather than using the `Makefile` directly, since the script is responsible to deal with Protobuf.

**Comment by sangjinhan** [comment]
Closing. Please feel free to reopen if necessary.
