### ISSUE TITLE
what the meaning of pkt_overhead?

### ISSUE THREAD

**Issue by GiantRice** [NetSys/bess#784]
Hi, all. I find that pkt_overhead in many modules with Runtask, which is 24 Byte.
For Ethernet frame, I know there are  7 bytes of preamble and 1 byte of SFD (start of frame delimiter) plus 12 byte of IFG (inter-frame gap). Total is 20 byte. So what dose the other four byte represent?

**Comment by sangjinhan** [comment]
That is for the 4-byte Ethernet frame CRC, which comes right after the Ethernet frame.

**Comment by GiantRice** [comment]
Oh, I see, thanks very much.
