### ISSUE TITLE
Queue.set_size() error

### ISSUE THREAD

**Issue by levaitamas** [NetSys/bess#801]
Hi,

Queue.set_size() seems broken:

```
<disconnected> $ daemon start
Done.
localhost:10514 $ run q
*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/home/levai/bess/bessctl/conf/q.bess", line 1, in <module>
    Queue().set_size(512)
TypeError: <lambda>() takes exactly 1 argument (2 given)
Placement violations found
constraints violated for module queue0 -- please check bessd log
```

A simple (or probably the simplest) .bess to reproduce the error:
```python
Queue().set_size(512)
```

BESS: v0.3.0-563-gdc98932
grpc: 1.10.0

**Comment by sangjinhan** [comment]
It should be `Queue().set_size(size=512)`. All arguments to module commands are supposed to be given with a keyword. I have to admit that the error message there is not the most explanatory.

By the way, you can also set the queue size when you create one, e.g., `Queue(size=256)`.
