### ISSUE TITLE
hashLB setgates CLI error

### ISSUE THREAD

**Issue by Linerd** [NetSys/bess#823]
I was running the sample hlb script, and I tried to modify the gates by executing the following:
command module hlb set_gates HashLBCommandSetGatesArg [0,1]

and the error is as follows:
Traceback (most recent call last):
  File "./bessctl", line 186, in <module>
    main()
  File "./bessctl", line 170, in main
    run_cli()
  File "./bessctl", line 159, in run_cli
    cli.loop()
  File "./bessctl", line 134, in loop
    super(BESSCLI, self).loop()
  File "/home/vagrant/bess/bessctl/cli.py", line 528, in loop
    self.process_one_line()
  File "/home/vagrant/bess/bessctl/cli.py", line 440, in process_one_line
    self.call_func(func, args)
  File "./bessctl", line 95, in call_func
    super(BESSCLI, self).call_func(func, args)
  File "/home/vagrant/bess/bessctl/cli.py", line 411, in call_func
    func(*args)
  File "/home/vagrant/bess/bessctl/commands.py", line 982, in command_module
    ret = cli.bess.run_module_command(module, cmd, arg_type, args)
  File "/home/vagrant/bess/bessctl/../pybess/bess.py", line 475, in run_module_command
    arg_msg = pb_conv.dict_to_protobuf(message_type, arg)
  File "/home/vagrant/bess/bessctl/../pybess/protobuf_to_dict.py", line 151, in dict_to_protobuf
    return _dict_to_protobuf(instance, values, type_callable_map, strict)
  File "/home/vagrant/bess/bessctl/../pybess/protobuf_to_dict.py", line 186, in _dict_to_protobuf
    fields = _get_field_mapping(pb, value, strict)
  File "/home/vagrant/bess/bessctl/../pybess/protobuf_to_dict.py", line 156, in _get_field_mapping
    for key, value in dict_value.items():
AttributeError: 'list' object has no attribute 'items'

if I type the following:
command module hlb set_gates HashLBCommandSetGatesArg
then only gate 0 is getting the traffic, no error.

Maybe I didn't get the format right? I tried multiple other options but they didn't work either.
Would love to see a documentation for the CLI operations... Thanks

**Comment by Linerd** [comment]
Ok, after many many trials, I finally found the correct format:
**command module hlb set_gates HashLBCommandSetGatesArg {'gates':[1,2]}**
In case anyone needs it...

**Comment by sangjinhan** [comment]
Yeah, all command arguments are supposed to be a dictionary in Python syntax, like {'key1': value1, 'key2:': value2, ...} Though sending commands via bessctl was meant to be mostly a "debugging" feature. The recommended way of doing it is something like `hlb.set_gates(gates=[1, 2])` with the pybess API.

**Comment by Linerd** [comment]
is the pybess API the same thing as configurations scripts? Forgive me if this is a dumb question, coz I was trying to find a way to configure the modules at runtime

**Comment by sangjinhan** [comment]
Actually the pybess API has never been well documented. You can think of bessctl as one example application using the API. The following is a small yet fully functional standalone script to demonstrate it:
```
#!/usr/bin/env python

import time
import sys

try:
    sys.path.insert(1, '/home/sangjin/bess')
    from pybess.bess import *
except ImportError:
    print >> sys.stderr, 'Cannot import the API module (pybess)'
    raise

bess = BESS()
bess.connect('localhost:10514')
bess.reset_all()

bess.create_module('Source', 'src')
bess.create_module('RoundRobin', 'rr')
bess.create_module('Sink', 'sink0')
bess.create_module('Sink', 'sink1')

bess.connect_modules('src', 'rr')
bess.connect_modules('rr', 'sink0', 0)
bess.connect_modules('rr', 'sink1', 1)

for i in range(1000):
    bess.run_module_command('rr', 'set_gates', 'RoundRobinCommandSetGatesArg',
                            {'gates': [i % 2]})
    bess.resume_all()
    time.sleep(0.8)
    bess.pause_all()
```
This script will alternate traffic between sink0 and sink1 (you can see with `bessctl monitor pipeline`). The API is not quite Pythonic at the moment, though. For example, you can do `rr.set_gates(gates=[1, 2])` in a bessctl configuration file, but you have to use the ugly `bess.run_module_command(...)` as above in a standalone application (controller).

**Comment by Linerd** [comment]
so if I understand it correctly, I can use this script as a "SDN-application" like app for run-time configuration? (given that I remove the create_module and connect_module parts)

**Comment by sangjinhan** [comment]
Yes, exactly. You will want to remove `reset_all()` as well. Everything you can do with bessctl can be done with `pybess/bess.py` too.

**Comment by Linerd** [comment]
@sangjinhan thanks a lot, I am getting a grasp on it. One quick question, is there a more efficient way to get the topology of the dataplane than calling get_module_info iteratively to construct it?

**Comment by sangjinhan** [comment]
I am afraid there is not :(

**Comment by Linerd** [comment]
@sangjinhan that is a pity. But how is the monitor pipeline graph drawn? The same inefficient way?

**Comment by sangjinhan** [comment]
Yes, monitor pipeline works that way (`command.py`). A new gRPC method contribution would be more than welcome!
