### ISSUE TITLE
BESS throughput 

### ISSUE THREAD

**Issue by konnekapm** [NetSys/bess#832]
Hi all, 

We setup BESS for VM to VM communication as described in pages . With IPERF tests , throughput is 16 gbps

Then , we setup 4 VM in same config , VM1--> VM2 and VM3-->VM4  each throughput 7,8 gbps . 

Is there anyway for increase these limits  ? 

Thank you .

**Comment by sangjinhan** [comment]
The bottleneck of virtio performance is memory copy, so in general it's fairly impossible to improve per-core throughput (unless you want to try zero-copy things). One thing you can do though is to add more cores. If you add the following at the beginning of your .bess file:

```
bess.add_worker(wid=0, core=0)
bess.add_worker(wid=1, core=1)
```

You should see the throughput roughly doubled (check with `bessctl monitor tc` if the both of cores are being utilized)
