### ISSUE TITLE
Max PMDPort number

### ISSUE THREAD

**Issue by konnekapm** [NetSys/bess#847]
Hi,
We couldnt create PMDPort more than 32
 
When we try to create hundreds virtual ports in bess script
sock1::PMDPort(vdev='eth_vhost1,iface=/tmp/test1.sock,queues=1')
sock2::PMDPort(vdev='eth_vhost2,iface=/tmp/test2.sock,queues=1')
...
sock33::PMDPort(vdev='eth_vhost33,iface=/tmp/test33.sock,queues=1')
..

Then we are getting below error
*** Error: Cannot attach vdev eth_vhost33,iface=/tmp/test33.sock,queues=1
  BESS daemon response - errno=19 (ENODEV: No such device)
       query: CreatePort
   query_arg: {'driver': 'PMDPort', 'name': 'sock33', 'arg': {'type_url': 'type.googleapis.com/bess.pb.PMDPortArg', 'value': '"+eth_vhost33,iface=/tmp/test33.sock,queues=1'}}

So, We are wondering that is there any limit about creating vhost-user socket creation ?

**Comment by ddiproietto** [comment]
I suspect the limit of 32 ports comes from DPDK:

`CONFIG_RTE_MAX_ETHPORTS=32`

from

https://git.dpdk.org/dpdk-stable/tree/config/common_base?id=d84aad650401a122cb75bd5811e49b03ef3dc49d#n140

Can you try changing that config option and recompiling? (There might be other limits I don't know about in DPDK or in BESS)

**Comment by konnekapm** [comment]
Thank you for your quick reply, you are right

we changed CONFIG_RTE_MAX_ETHPORTS to 1024 for testing purposes.
then now we can create 256 ports. Then below error occurs
`
*** Error: rte_eth_dev_configure() failed
  BESS daemon response - errno=16 (EBUSY: Device or resource busy)
       query: CreatePort
   query_arg: {'driver': 'PMDPort', 'name': 'sock257', 'arg': {'type_url': 'type.googleapis.com/bess.pb.PMDPortArg', 'value': '"-eth_vhost257,iface=/tmp/test257.sock,queues=1'}}`

There should be another limit in DPDK also. 
It might be another MAX option in DPDK. 
Now, we are looking for it

**Comment by chris3torek** [comment]
Port IDs inside DPDK are stored in an eight bit (`unsigned char`) field, so there is a hard limit of 256.

**Comment by ddiproietto** [comment]
Looks like newer versions of DPDK store it as `uint16_t`.

Maybe we can update the DPDK version used by BESS when 18.11 (the new LTS) is released? (I don't know of any specific plans though)
