### ISSUE TITLE
BESS cannot work with Mellanox NIC card with DPDK 17.11

### ISSUE THREAD

**Issue by janeyen** [NetSys/bess#856]
Hi,

We've tried to compile up-to-date BESS with Mellanox Connectx-5 NIC card but failed. Mellanox NIC card has to work with Mellanox driver which should be installed with Mellanox OFED. For DPDK 17.11, the OFED installation procedure will install different libraries compared to DPDK 17.05. (The installation procedure requires flags of upstream library) But in BESS build.py, it still tries to retrieve the information that's only available for versions before 17.11 to decide whether Mellanox libraries are successfully installed. 

We've done several trials and are able to compiled DPDK successfully with appropriate drivers and libraries, but we failed to build/compile BESS daemon. Could you please check on this issue? Thanks.

**Comment by sangjinhan** [comment]
Thank you for reporting this. I made a patch for the issue (#860), which seemed to solve the issue on my test system. With the fixed code, on a fresh VM running Ubuntu 16.04, I did the following steps:

1. Download `MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64.tgz` and extract
1. Build and install with `sudo ./mlnxofedinstall --dpdk --upstream-libs`
1. Install the latest version of Ansible (via ppa), then install dependencies with `env/build-dep.yml`
1. Run `bess/build.py`. Both DPDK and BESS are built fine.

Which OS distro and OFED version did you use? It would be great if you can try it again with the patched `build.py`.

**Comment by janeyen** [comment]
Thank you so much. I just applied the patch and BESS built successfully. Our OS is also running on Ubuntu 16.04 and I tried the exact version you suggested.

**Comment by sangjinhan** [comment]
Thanks for confirming!
