### ISSUE TITLE
bess::Packet::from_paddr() returns nullptr

### ISSUE THREAD

**Issue by wjuni** [NetSys/bess#873]
Hi,
I've been using an old version of BESS, but I'm trying to move to the recent version.
However, when I try to run my script, BESS encounters segfault.
Script that I'm using looks like this:
```
host_if1 = VPort(ifname="bess1", ip_addrs='10.0.0.2')
nic_if1 = PMDPort(port_id=0)
PortInc(port=host_if1) -> PortOut(port=nic_if1)
PortInc(port=nic_if1) -> PortOut(port=host_if1)
````
The symptom is similar to #722, but I soon found out that `bess::Packet::from_paddr()` always returns a null pointer. `bess::Packet::from_paddr()` looks up `pframe_pool`, but the static variable `pframe_pool` of the core/packet.cc doesn't seem to be initialized (or assigned), which makes it return null pointer. I guess the behavior had changed after #820 (Introduction of PacketPool), but I don't know how to fix it.

Since `VPort::RecvPackets()` from core/drivers/vport.cc uses `bess::Packet::from_paddr()`, I guess I'm encountering segfaults when I try to use VPort.

**Comment by nrdmao** [comment]
I am seeing this problem as well. This fundamentally breaks the vport driver. Is anyone working on it? Yes, it seems to be associated with the introduction of PacketPool. Only the vport driver uses from_paddr() as far as I can tell.

**Comment by nrdmao** [comment]
I uploaded a patch for this. Hopefully someone can review and approve. Thanks!
