### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by TCZWJ** [NetSys/bess#913]
Building BESS daemon...
Log:
 make: Entering directory '/home/zwj/bess/core'
[LD]        bessd
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_wrapper.o): In function `grpc_resolve_address_ares_impl':
(.text+0x2dd): undefined reference to `ares_gethostbyname'
(.text+0x32f): undefined reference to `ares_gethostbyname'
(.text+0x50b): undefined reference to `ares_strerror'
(.text+0x699): undefined reference to `ares_inet_ntop'
(.text+0x775): undefined reference to `ares_inet_ntop'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_wrapper.o): In function `grpc_ares_init':
(.text+0x84a): undefined reference to `ares_library_init'
(.text+0x867): undefined reference to `ares_strerror'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_wrapper.o): In function `grpc_ares_cleanup':
(.text+0x921): undefined reference to `ares_library_cleanup'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_ev_driver_posix.o):(.text+0x1f9): undefined reference to `ares_getsock'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_ev_driver_posix.o):(.text+0x58b): undefined reference to `ares_destroy'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_ev_driver_posix.o):(.text+0x631): undefined reference to `ares_cancel'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_ev_driver_posix.o):(.text+0x67d): undefined reference to `ares_process_fd'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_ev_driver_posix.o):(.text+0x6f1): undefined reference to `ares_cancel'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_ev_driver_posix.o):(.text+0x73d): undefined reference to `ares_process_fd'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgrpc.a(grpc_ares_ev_driver_posix.o): In function `grpc_ares_ev_driver_create':
(.text+0x77f): undefined reference to `ares_init'
(.text+0x7ac): undefined reference to `ares_strerror'
collect2: error: ld returned 1 exit status
Error: bessd
-----------------------------------------------------------
As above infomation, after i have done all things, the link error throw out.

**Comment by TCZWJ** [comment]
After the OS was reinstalled, the problem was solved.

**Comment by sangjinhan** [comment]
Perhaps the issue was that `libc-ares-dev` package is not available.
