### ISSUE TITLE
a little test of bess and ovs-dpdk

### ISSUE THREAD

**Issue by zym-ustc** [NetSys/bess#93]
The performance of bess is not better than that of ovs-dpdk. Is there any problem in my configuration? And is the experimental environment suitable for bess?

##### environment
```
Linux  4.4.0-45-generic
Memory: 8G
Ethernet controller: Intel Corporation 82572EI Gigabit Ethernet Controller (Copper)
```

##### 1.1 configuration of bess
>```
#sysctl -w vm.nr_hugepages=2048
#modprobe uio_pci_generic
#bin/dpdk_devbind.py -b uio_pci_generic 03:00.0
#bin/bessd
#bin/bessctl
$run sample/vport
#ifconfig vport0 133.133.134.124/16
```

##### 1.2 configuration of ovs-dpdk
```
#mkdir -p /usr/local/etc/openvswitch
#mkdir -p /usr/local/var/run/openvswitch
#ovsdb-tool create /usr/local/etc/openvswitch/conf.db /usr/local/share/openvswitch/vswitch.ovsschema
#sudo ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile --detach
#ovs-vsctl --no-wait init

#sysctl vm.nr_hugepages=2048
#mkdir -p /dev/hugepages
#mount -t hugetlbfs hugetlbfs /dev/hugepages
#modprobe uio_pci_generic
#ifconfig enp3s0 down
#$DPDK_DIR/tools/dpdk-devbind.py -b uio_pci_generic 03:00.0

#ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-init=true
#ovs-vswitchd unix:$DB_SOCK --pidfile --detach

#ovs-vsctl add-br br0 -- set bridge br0 datapath_type=netdev
#ovs-vsctl add-port br0 dpdk0 -- set Interface dpdk0 type=dpdk

#ifconfig br0 up
#ifconfig br0 133.133.134.126/16
```
### 2. result:
##### 2.1 phy-phy   
>```ping 0.65ms```

```
# iperf -c 133.133.134.124 -p12345 -i -1 -t 10 -w 1K
WARNING: interval too small, increasing from -1.00 to 0.5 seconds.
WARNING: TCP window size set to 1024 bytes. A small window size
will give poor performance. See the Iperf documentation.
------------------------------------------------------------
Client connecting to 133.133.134.124, TCP port 12345
TCP window size: 4.50 KByte (WARNING: requested 1.00 KByte)
------------------------------------------------------------
[ 3] local 133.133.134.72 port 35558 connected with 133.133.134.124 port 12345
[ ID] Interval Transfer Bandwidth
[ 3] 0.0- 0.5 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 0.5- 1.0 sec 5.12 MBytes 86.0 Mbits/sec
[ 3] 1.0- 1.5 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 1.5- 2.0 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 2.0- 2.5 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 2.5- 3.0 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 3.0- 3.5 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 3.5- 4.0 sec 4.75 MBytes 79.7 Mbits/sec
[ 3] 4.0- 4.5 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 4.5- 5.0 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 5.0- 5.5 sec 4.75 MBytes 79.7 Mbits/sec
[ 3] 5.5- 6.0 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 6.0- 6.5 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 6.5- 7.0 sec 4.75 MBytes 79.7 Mbits/sec
[ 3] 7.0- 7.5 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 7.5- 8.0 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 8.0- 8.5 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 8.5- 9.0 sec 4.75 MBytes 79.7 Mbits/sec
[ 3] 9.0- 9.5 sec 4.88 MBytes 81.8 Mbits/sec
[ 3] 9.5-10.0 sec 4.75 MBytes 79.7 Mbits/sec
[ 3] 0.0-10.0 sec 97.8 MBytes 81.9 Mbits/sec
```



##### 2.2 bess
>```ping 0.28ms```

```
# iperf -c 133.133.134.126 -p12345 -i -1 -t 10 -w 1k
WARNING: interval too small, increasing from -1.00 to 0.5 seconds.
WARNING: TCP window size set to 1024 bytes. A small window size
will give poor performance. See the Iperf documentation.
------------------------------------------------------------
Client connecting to 133.133.134.126, TCP port 12345
TCP window size: 4.50 KByte (WARNING: requested 1.00 KByte)
------------------------------------------------------------
[ 3] local 133.133.134.127 port 57700 connected with 133.133.134.126 port 12345
[ ID] Interval Transfer Bandwidth
[ 3] 0.0- 0.5 sec 1.38 MBytes 23.1 Mbits/sec
[ 3] 0.5- 1.0 sec 1.12 MBytes 18.9 Mbits/sec
[ 3] 1.0- 1.5 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 1.5- 2.0 sec 1.12 MBytes 18.9 Mbits/sec
[ 3] 2.0- 2.5 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 2.5- 3.0 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 3.0- 3.5 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 3.5- 4.0 sec 1.12 MBytes 18.9 Mbits/sec
[ 3] 4.0- 4.5 sec 1.12 MBytes 18.9 Mbits/sec
[ 3] 4.5- 5.0 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 5.0- 5.5 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 5.5- 6.0 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 6.0- 6.5 sec 1.12 MBytes 18.9 Mbits/sec
[ 3] 6.5- 7.0 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 7.0- 7.5 sec 1.12 MBytes 18.9 Mbits/sec
[ 3] 7.5- 8.0 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 8.0- 8.5 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 8.5- 9.0 sec 1.12 MBytes 18.9 Mbits/sec
[ 3] 9.0- 9.5 sec 1.25 MBytes 21.0 Mbits/sec
[ 3] 9.5-10.0 sec 1.12 MBytes 18.9 Mbits/sec
[ 3] 0.0-10.0 sec 24.2 MBytes 20.2 Mbits/sec
```

##### 2.3 ovs-dpdk
>```ping 0.28ms```

```
# iperf -c 133.133.134.126 -p12345 -i -1 -t 10 -w 1K
WARNING: interval too small, increasing from -1.00 to 0.5 seconds.
WARNING: TCP window size set to 1024 bytes. A small window size
will give poor performance. See the Iperf documentation.
------------------------------------------------------------
Client connecting to 133.133.134.126, TCP port 12345
TCP window size: 4.50 KByte (WARNING: requested 1.00 KByte)
------------------------------------------------------------
[ 3] local 133.133.134.127 port 52702 connected with 133.133.134.126 port 12345
[ ID] Interval Transfer Bandwidth
[ 3] 0.0- 0.5 sec 5.50 MBytes 92.3 Mbits/sec
[ 3] 0.5- 1.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 1.0- 1.5 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 1.5- 2.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 2.0- 2.5 sec 5.50 MBytes 92.3 Mbits/sec
[ 3] 2.5- 3.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 3.0- 3.5 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 3.5- 4.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 4.0- 4.5 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 4.5- 5.0 sec 5.25 MBytes 88.1 Mbits/sec
[ 3] 5.0- 5.5 sec 5.50 MBytes 92.3 Mbits/sec
[ 3] 5.5- 6.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 6.0- 6.5 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 6.5- 7.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 7.0- 7.5 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 7.5- 8.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 8.0- 8.5 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 8.5- 9.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 9.0- 9.5 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 9.5-10.0 sec 5.38 MBytes 90.2 Mbits/sec
[ 3] 0.0-10.0 sec 108 MBytes 90.4 Mbits/sec
```

**Comment by sangjinhan** [comment]
There are so many variables that can affect the throughput of a TCP connection, so I cannot tell what the exact reason is. In your case, the performance limiting bottleneck is the small TCP window size (as the warning message indicates), since it is smaller than the [bandwidth delay product](https://en.wikipedia.org/wiki/Bandwidth-delay_product).

By setting the "-w 1k" option, the effective window size in the kernel is 2 MSS (2 * 1448 bytes), since it is the lowest allowed value and 1k is out of the range. This means, at any given time, there will be only two packets in transit, and the RTT is the limiting factor. You can reduce RTT arbitrarily, but you can increase the size of 

Let's look at my testcase.

On the server side (running a linux device driver):
```sh
$ sudo ethtool -C p513p1 rx-usecs 0  # this is necessary otherwise the RTT will fluctuate a lot nondeterministically
$ iperf -s
```

In the client (running BESS)
```sh
$ iperf -c 10.0.0.2 -i 1 -t 100 -m -w 1k
WARNING: TCP window size set to 1024 bytes. A small window size
will give poor performance. See the Iperf documentation.
------------------------------------------------------------
Client connecting to 10.0.0.2, TCP port 5001
TCP window size: 4.50 KByte (WARNING: requested 1.00 KByte)
------------------------------------------------------------
[  3] local 10.0.0.1 port 48024 connected with 10.0.0.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 1.0 sec  71.0 MBytes   596 Mbits/sec
[  3]  1.0- 2.0 sec  88.5 MBytes   742 Mbits/sec
[  3]  2.0- 3.0 sec  88.4 MBytes   741 Mbits/sec
[  3]  3.0- 4.0 sec  85.1 MBytes   714 Mbits/sec
[  3]  4.0- 5.0 sec  92.0 MBytes   772 Mbits/sec
[  3]  5.0- 6.0 sec  74.4 MBytes   624 Mbits/sec
[  3]  6.0- 7.0 sec  81.6 MBytes   685 Mbits/sec
[  3]  7.0- 8.0 sec  88.4 MBytes   741 Mbits/sec
[  3]  8.0- 9.0 sec  81.4 MBytes   683 Mbits/sec
[  3]  9.0-10.0 sec  91.0 MBytes   763 Mbits/sec
[  3] 10.0-11.0 sec  85.9 MBytes   720 Mbits/sec
[  3] 11.0-12.0 sec  91.9 MBytes   771 Mbits/sec
[  3] 12.0-13.0 sec  88.6 MBytes   743 Mbits/sec
```

`tcpdump` showed around 30us RTT (although it varies every round), so:
1448 * 2 / 0.000030 = 92MB/s

which is (ballpark-y) consistent with the result.

---

The reason why the linux driver and ovs-dpdk shows higher throughput is TCP segmentation offloading (TSO):

17:19:29.599233 00:1e:67:9f:4d:9e > 00:1e:67:9f:4d:ae, ethertype IPv4 (0x0800), length 65226: 10.0.0.1.48028 > 10.0.0.2.5001: Flags [.], seq 43441:108601, ack 0, win 229, options [nop,nop,TS val 295306163 ecr 2204200898], length 65160

Linux transmits 64KB packets when TSO is enabled, which is temporarily violating the TCP window size limit.

**Comment by sangjinhan** [comment]
tl, dr; increase the window size :)
