### ISSUE TITLE
How  to call the functions of modules at run time?

### ISSUE THREAD

**Issue by JanonWang** [NetSys/bess#933]
For example, I would like to add a rule for ExactMatch module at run time. However, we can only call the add function in BESS configuration script and the pipeline is established after the script finishes. Hence, how can I call a function of the modules after the pipeline is established?

**Comment by etremblay18** [comment]
BESS exposes a gRPC API that can be used at runtime to call commands on a module (see https://github.com/NetSys/bess/blob/master/protobuf/service.proto#L288). This allows you to define a controller in the language of your choice (that is supported by gRPC) that can add rules at runtime. BESS provides a basic controller called bessctl (written in python) that allows you to call this API from the command line. bessctl is found in the bin directory and should automatically connect to your running bessd instance when you launch it.

Adding a rule to an ExactMatch module would look something like:
```
localhost:10514 $ command module myExactMatch add ExactMatchCommandAddArg {"gate": 0, "fields": [{"value_int": 10}]}
```

Note that if the command you are trying to call is not thread-safe (which is currently the case for the ExactMatch module's add command), you will need to pause the workers before calling it. This can also be done using bessctl.

**Comment by magaboomchen** [comment]
Hi! Thanks for your help. @etremblay18 @sangjinhan 
I want to control bess from a remote client which use the following client.py:
```
from __future__ import print_function
import logging

import grpc

import service_pb2
import service_pb2_grpc
import bess_msg_pb2

def run():
    # NOTE(gRPC Python Team): .close() is possible on a channel and should be
    # used in circumstances in which the with statement does not fit the needs
    # of the code.
    with grpc.insecure_channel('localhost:10514') as channel:
        stub = service_pb2_grpc.BESSControlStub(channel)
        response = stub.GetVersion(bess_msg_pb2.EmptyRequest() )
    print("Greeter client received: " + response.version)

if __name__ == '__main__':
    logging.basicConfig()
    run()
```

I test this code on server and it work well.
However, I get error when I run this code on client by replacing the "localhost:10514" to "$ServerIP:10514". 
The error message is here:

> E0225 17:59:17.149109543   11325 http_proxy.cc:67]           'https' scheme not supported in proxy URI
> Traceback (most recent call last):
>   File "./greet_client.py", line 40, in <module>
>     run()
>   File "./greet_client.py", line 31, in run
>     response = stub.GetVersion(bess_msg_pb2.EmptyRequest() )
>   File "/home/t1/.local/lib/python2.7/site-packages/grpc/_channel.py", line 826, in __call__
>     return _end_unary_response_blocking(state, call, False, None)
>   File "/home/t1/.local/lib/python2.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
>     raise _InactiveRpcError(state)
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> 	status = StatusCode.UNAVAILABLE
> 	details = "failed to connect to all addresses"
> 	debug_error_string = "{"created":"@1582624757.159120017","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1582624757.159113961","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
> >

Does anyone know how to fix this problem?
Can we control bess from a remote client?
Thx!
