### ISSUE TITLE
Question about calculating bandwidth `Mbps` in `monitor port` command

### ISSUE THREAD

**Issue by sarsanaee** [NetSys/bess#988]
Hello all,

I'm actually writing my own rate prober and I was verifying it with what BESS is reporting in `monitor port`. I just realized that my number are different than BESS. Then I looked into how BESS is actually calculating those number and I ended up here:
https://github.com/NetSys/bess/blob/bf17211dd1f7a7c77e9bf5b3c624aaf39f1b88b1/bessctl/commands.py#L1783

I don't understand why `delta.inc_packets * 24` is added to `delta.inc_bytes` for `inc_mbps`. What is the rationale here?

Thanks,
Alireza

**Comment by chris3torek** [comment]
This 24 accounts for Ethernet overhead (L1 data) not visible in the packet bytes even when looking at the L2 headers. (There are 8 octets of preamble and start-of-frame, and then 4 octets of frame CRC and 12 more of interpacket gap.  See [WIkipedia](https://en.wikipedia.org/wiki/Ethernet_frame) for illustration.)
