### ISSUE TITLE
Sample plugin SequentialUpdate does not exist

### ISSUE THREAD

**Issue by krsna1729** [NetSys/bess#992]
```
./build.py --plugin sample_plugin bess
```

Running https://github.com/NetSys/bess/blob/master/sample_plugin/bessctl_conf/sequential_update.bess
```
*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/opt/bess/bessctl/conf/su.bess", line 49, in <module>
    -> Sink()
  File "/opt/bess/bessctl/commands.py", line 134, in __bess_module__
    raise ConfError("Module class %s does not exist" % mclass_name)
ConfError: Module class SequentialUpdate does not exist
```

```
./bessctl show mclass

RoundRobin       splits packets evenly with round robin
SetMetadata      Set metadata attributes to packets
Sink             discards all packets
Source           infinitely generates packets with uninitialized data
Split            split packets depending on packet data or metadata attributes
StaticNAT        Static network address translator
Timestamp        marks current time to packets (paired with Measure module)
```

**Comment by chris3torek** [comment]
It looks like a glitch in the C++ code, which calls the module `"supdate"` rather than `"SequentialUpdate"` (or if you prefer you could modify the `.bess` file to use `supdate` instead of `SequentialUpdate`).

**Comment by krsna1729** [comment]
```
*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/opt/bess/bessctl/conf/su.bess", line 49, in <module>
    -> Sink()
  File "/opt/bess/bessctl/commands.py", line 134, in __bess_module__
    raise ConfError("Module class %s does not exist" % mclass_name)
ConfError: Module class supdate does not exist
  Command failed: run su
```

**Comment by krsna1729** [comment]
https://github.com/NetSys/bess/blob/a5708332826880a77a4d8f3f63c53e4a5ebc96d8/bessctl/commands.py#L807

If `show mclass` /`ListMclass` is not showing SequentialUpdate nor supdate, it wont work?

**Comment by chris3torek** [comment]
Oh, yes, you're right - even though there's a mismatch, the name `supdate` should have been in the class list.  I'm not sure what is happening, then - it's acting like the sample plugins were not built.

**Comment by krsna1729** [comment]
Yes its behaving like that, but i feel is compiled in

```
# strings /bin/bessd | grep -i sequentialupdate | wc -l
511

# ls pybess/plugin_pb/
__init__.py  __init__.pyc  ports  supdate_msg_pb2.py  supdate_msg_pb2.pyc  supdate_msg_pb2_grpc.py
```

**Comment by chris3torek** [comment]
Hm, and on further investigation, my off-the-cuff answer was wrong - the module declaration itself uses the string literal as a name template for _instances_, the name will be `SequentialUpdate`. Something is happening such that the registration of the module is not working.

**Comment by nevelis** [comment]
Has there been any progress on solving this?  I ran into this same thing last week, I see the strings in the binary & I see the protobuf file in pybess in the right place but I get the same "Module class does not exist" error.

**Comment by krsna1729** [comment]
@chris3torek this might be limited to [our env](https://github.com/omec-project/upf-epc/blob/master/Dockerfile#L63-L67) (same as @nevelis )

When building from bess repo 

```
container_build.py shell
build.py --plugin sample_plugin bess
```

its fine

```
RoundRobin       splits packets evenly with round robin
SequentialUpdate updates packet data sequentially in a range
SetMetadata      Set metadata attributes to packets
```

**Comment by krsna1729** [comment]
weirdest thing - 

If I run `./bin/bessd` or `./core/bessd` I can see sequential update.
If I copy it to /bin or anywhere else and run I cannot see sequential update 

```dockerfile
FROM nefelinetworks/bess_build AS bess-build
RUN apt-get update && apt-get install -y wget unzip ca-certificates
ARG BESS_COMMIT=master
RUN wget -qO bess.zip https://github.com/NetSys/bess/archive/${BESS_COMMIT}.zip && unzip bess.zip
WORKDIR bess-${BESS_COMMIT}
RUN ./build.py --plugin sample_plugin bess && \
    cp bin/bessd /bin
```

**Comment by krsna1729** [comment]
need to copy the modules folder and it works

**Comment by chris3torek** [comment]
> need to copy the modules folder and it works

Aha, yes, that's what was missing from the report - the modules are loaded at runtime so they must be present.

**Comment by krsna1729** [comment]
@chris3torek running strings on bessd binary showed so many occurrences which led me to believe it was compiled in.
